INSERT INTO HOBBY (name,description)  VALUES ('3D-udskrivning','https://en.wikipedia.org/wiki/3D_printing');
INSERT INTO HOBBY (name,description)  VALUES ('Akrobatik','https://en.wikipedia.org/wiki/Acrobatics');
INSERT INTO HOBBY (name,description)  VALUES ('Skuespil','https://en.wikipedia.org/wiki/Acting');
INSERT INTO HOBBY (name,description)  VALUES ('Amatørradio','https://en.wikipedia.org/wiki/Amateur_radio');
INSERT INTO HOBBY (name,description)  VALUES ('Animation','https://en.wikipedia.org/wiki/Animation');
INSERT INTO HOBBY (name,description)  VALUES ('Aquascaping','https://en.wikipedia.org/wiki/Aquascaping');
INSERT INTO HOBBY (name,description)  VALUES ('Astrologi','https://en.wikipedia.org/wiki/Astrology');
INSERT INTO HOBBY (name,description)  VALUES ('Bagning','https://en.wikipedia.org/wiki/Baking');
INSERT INTO HOBBY (name,description)  VALUES ('Baton snurrer','https://en.wikipedia.org/wiki/Baton_twirling');
INSERT INTO HOBBY (name,description)  VALUES ('Blogging','https://en.wikipedia.org/wiki/Blogging');
INSERT INTO HOBBY (name,description)  VALUES ('Brætspil','https://en.wikipedia.org/wiki/Board_game');
INSERT INTO HOBBY (name,description)  VALUES ('Bogdiskussionsklub','https://en.wikipedia.org/wiki/Book_discussion_club');
INSERT INTO HOBBY (name,description)  VALUES ('Gendannelse af bøger','https://en.wikipedia.org/wiki/Book_restoration');
INSERT INTO HOBBY (name,description)  VALUES ('Bowling','https://en.wikipedia.org/wiki/Bowling');
INSERT INTO HOBBY (name,description)  VALUES ('Brasiliansk jiu-jitsu','https://en.wikipedia.org/wiki/Brazilian_jiu-jitsu');
INSERT INTO HOBBY (name,description)  VALUES ('Brødfremstilling','https://en.wikipedia.org/wiki/Breadmaking');
INSERT INTO HOBBY (name,description)  VALUES ('Bygning','https://en.wikipedia.org/wiki/Building');
INSERT INTO HOBBY (name,description)  VALUES ('Bullet Journal','https://en.wikipedia.org/wiki/Bullet_Journal');
INSERT INTO HOBBY (name,description)  VALUES ('Cabaret','https://en.wikipedia.org/wiki/Cabaret');
INSERT INTO HOBBY (name,description)  VALUES ('Kalligrafi','https://en.wikipedia.org/wiki/Calligraphy');
INSERT INTO HOBBY (name,description)  VALUES ('Lysfremstilling','https://en.wikipedia.org/wiki/Candle_making');
INSERT INTO HOBBY (name,description)  VALUES ('Slikfremstilling','https://en.wikipedia.org/wiki/Candy_making');
INSERT INTO HOBBY (name,description)  VALUES ('Bil','https://en.wikipedia.org/wiki/Car');
INSERT INTO HOBBY (name,description)  VALUES ('Kortspil','https://en.wikipedia.org/wiki/Card_games');
INSERT INTO HOBBY (name,description)  VALUES ('Cardistry','https://en.wikipedia.org/wiki/Cardistry');
INSERT INTO HOBBY (name,description)  VALUES ('Ostemagning','https://en.wikipedia.org/wiki/Cheesemaking');
INSERT INTO HOBBY (name,description)  VALUES ('Rengøring','https://en.wikipedia.org/wiki/Cleaning');
INSERT INTO HOBBY (name,description)  VALUES ('Tøj','https://en.wikipedia.org/wiki/Clothing');
INSERT INTO HOBBY (name,description)  VALUES ('Hjemmelavet kaffe','https://en.wikipedia.org/wiki/Home_roasting_coffee');
INSERT INTO HOBBY (name,description)  VALUES ('Indsamling','https://en.wikipedia.org/wiki/Collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Malebog','https://en.wikipedia.org/wiki/Coloring_book');
INSERT INTO HOBBY (name,description)  VALUES ('Computer programmering','https://en.wikipedia.org/wiki/Computer_programming');
INSERT INTO HOBBY (name,description)  VALUES ('Konfekture','https://en.wikipedia.org/wiki/Confectionery');
INSERT INTO HOBBY (name,description)  VALUES ('Madlavning','https://en.wikipedia.org/wiki/Cooking');
INSERT INTO HOBBY (name,description)  VALUES ('Cosplaying','https://en.wikipedia.org/wiki/Cosplaying');
INSERT INTO HOBBY (name,description)  VALUES ('Kuponering','https://en.wikipedia.org/wiki/Couponing');
INSERT INTO HOBBY (name,description)  VALUES ('Håndværk','https://en.wikipedia.org/wiki/Craft');
INSERT INTO HOBBY (name,description)  VALUES ('Kreativ skrivning','https://en.wikipedia.org/wiki/Creative_writing');
INSERT INTO HOBBY (name,description)  VALUES ('Hækling','https://en.wikipedia.org/wiki/Crocheting');
INSERT INTO HOBBY (name,description)  VALUES ('Korssting','https://en.wikipedia.org/wiki/Cross-stitch');
INSERT INTO HOBBY (name,description)  VALUES ('Krydsogtværs','https://en.wikipedia.org/wiki/Crossword_puzzles');
INSERT INTO HOBBY (name,description)  VALUES ('Kryptografi','https://en.wikipedia.org/wiki/Cryptography');
INSERT INTO HOBBY (name,description)  VALUES ('Cue sport','https://en.wikipedia.org/wiki/Cue_sports');
INSERT INTO HOBBY (name,description)  VALUES ('Dans','https://en.wikipedia.org/wiki/Dance');
INSERT INTO HOBBY (name,description)  VALUES ('Digital kunst','https://en.wikipedia.org/wiki/Digital_art');
INSERT INTO HOBBY (name,description)  VALUES ('Distro-hopping','https://en.wikipedia.org/wiki/Distro-hopping');
INSERT INTO HOBBY (name,description)  VALUES ('Disc-jockey','https://en.wikipedia.org/wiki/Disc-jockey');
INSERT INTO HOBBY (name,description)  VALUES ('Gør det selv','https://en.wikipedia.org/wiki/Do_it_yourself');
INSERT INTO HOBBY (name,description)  VALUES ('Drama','https://en.wikipedia.org/wiki/Drama');
INSERT INTO HOBBY (name,description)  VALUES ('Tegning','https://en.wikipedia.org/wiki/Drawing');
INSERT INTO HOBBY (name,description)  VALUES ('Blandet drik','https://en.wikipedia.org/wiki/Mixed_drink');
INSERT INTO HOBBY (name,description)  VALUES ('Drikker','https://en.wikipedia.org/wiki/Drinking');
INSERT INTO HOBBY (name,description)  VALUES ('Elektroniske spil','https://en.wikipedia.org/wiki/Electronic_games');
INSERT INTO HOBBY (name,description)  VALUES ('Elektronik','https://en.wikipedia.org/wiki/Electronics');
INSERT INTO HOBBY (name,description)  VALUES ('Broderi','https://en.wikipedia.org/wiki/Embroidery');
INSERT INTO HOBBY (name,description)  VALUES ('Eksperimenterer','https://en.wikipedia.org/wiki/Experimenting');
INSERT INTO HOBBY (name,description)  VALUES ('Fantasy sport','https://en.wikipedia.org/wiki/Fantasy_sport');
INSERT INTO HOBBY (name,description)  VALUES ('Mode','https://en.wikipedia.org/wiki/Fashion');
INSERT INTO HOBBY (name,description)  VALUES ('Mode design','https://en.wikipedia.org/wiki/Fashion_design');
INSERT INTO HOBBY (name,description)  VALUES ('Fiskearbejde','https://en.wikipedia.org/wiki/Fishkeeping');
INSERT INTO HOBBY (name,description)  VALUES ('Filmfremstilling','https://en.wikipedia.org/wiki/Filmmaking');
INSERT INTO HOBBY (name,description)  VALUES ('Blomsterbinding','https://en.wikipedia.org/wiki/Flower_arranging');
INSERT INTO HOBBY (name,description)  VALUES ('Fluebinding','https://en.wikipedia.org/wiki/Fly_tying');
INSERT INTO HOBBY (name,description)  VALUES ('Andet sprog erhvervelse','https://en.wikipedia.org/wiki/Second-language_acquisition');
INSERT INTO HOBBY (name,description)  VALUES ('Møbel','https://en.wikipedia.org/wiki/Furniture');
INSERT INTO HOBBY (name,description)  VALUES ('Spil','https://en.wikipedia.org/wiki/Games');
INSERT INTO HOBBY (name,description)  VALUES ('Bordspil','https://en.wikipedia.org/wiki/Tabletop_game');
INSERT INTO HOBBY (name,description)  VALUES ('Rollespil','https://en.wikipedia.org/wiki/Role-playing_game');
INSERT INTO HOBBY (name,description)  VALUES ('Slægtsforskning','https://en.wikipedia.org/wiki/Genealogy');
INSERT INTO HOBBY (name,description)  VALUES ('Honningkagehus','https://en.wikipedia.org/wiki/Gingerbread_house');
INSERT INTO HOBBY (name,description)  VALUES ('Glasblæsning','https://en.wikipedia.org/wiki/Glassblowing');
INSERT INTO HOBBY (name,description)  VALUES ('Grafisk design','https://en.wikipedia.org/wiki/Graphic_design');
INSERT INTO HOBBY (name,description)  VALUES ('Gunsmithing','https://en.wikipedia.org/wiki/Gunsmithing');
INSERT INTO HOBBY (name,description)  VALUES ('Gymnastik','https://en.wikipedia.org/wiki/Gymnastics');
INSERT INTO HOBBY (name,description)  VALUES ('Hacker','https://en.wikipedia.org/wiki/Hacker');
INSERT INTO HOBBY (name,description)  VALUES ('Herpetokultur','https://en.wikipedia.org/wiki/Herpetoculture');
INSERT INTO HOBBY (name,description)  VALUES ('Hjemmeforbedring','https://en.wikipedia.org/wiki/Home_improvement');
INSERT INTO HOBBY (name,description)  VALUES ('Hjemmebrygning','https://en.wikipedia.org/wiki/Homebrewing');
INSERT INTO HOBBY (name,description)  VALUES ('Pleje af husplanter','https://en.wikipedia.org/wiki/Houseplant_care');
INSERT INTO HOBBY (name,description)  VALUES ('Hula bøjning','https://en.wikipedia.org/wiki/Hula_hooping');
INSERT INTO HOBBY (name,description)  VALUES ('Humor','https://en.wikipedia.org/wiki/Humor');
INSERT INTO HOBBY (name,description)  VALUES ('Hydroponics','https://en.wikipedia.org/wiki/Hydroponics');
INSERT INTO HOBBY (name,description)  VALUES ('Skøjteløb','https://en.wikipedia.org/wiki/Ice_skating');
INSERT INTO HOBBY (name,description)  VALUES ('Smykkefremstilling','https://en.wikipedia.org/wiki/Jewelry_making');
INSERT INTO HOBBY (name,description)  VALUES ('Puslespil','https://en.wikipedia.org/wiki/Jigsaw_puzzles');
INSERT INTO HOBBY (name,description)  VALUES ('Dagbog','https://en.wikipedia.org/wiki/Diary');
INSERT INTO HOBBY (name,description)  VALUES ('Jonglere','https://en.wikipedia.org/wiki/Juggling');
INSERT INTO HOBBY (name,description)  VALUES ('Karaoke','https://en.wikipedia.org/wiki/Karaoke');
INSERT INTO HOBBY (name,description)  VALUES ('Karate','https://en.wikipedia.org/wiki/Karate');
INSERT INTO HOBBY (name,description)  VALUES ('Kendama','https://en.wikipedia.org/wiki/Kendama');
INSERT INTO HOBBY (name,description)  VALUES ('Knivfremstilling','https://en.wikipedia.org/wiki/Knife_making');
INSERT INTO HOBBY (name,description)  VALUES ('Strikning','https://en.wikipedia.org/wiki/Knitting');
INSERT INTO HOBBY (name,description)  VALUES ('Knude binder','https://en.wikipedia.org/wiki/Knot_tying');
INSERT INTO HOBBY (name,description)  VALUES ('Kombucha','https://en.wikipedia.org/wiki/Kombucha');
INSERT INTO HOBBY (name,description)  VALUES ('Blonder','https://en.wikipedia.org/wiki/Lace_making');
INSERT INTO HOBBY (name,description)  VALUES ('Lapidary','https://en.wikipedia.org/wiki/Lapidary');
INSERT INTO HOBBY (name,description)  VALUES ('Læder håndværk','https://en.wikipedia.org/wiki/Leather_crafting');
INSERT INTO HOBBY (name,description)  VALUES ('Lego','https://en.wikipedia.org/wiki/Lego');
INSERT INTO HOBBY (name,description)  VALUES ('musik','https://en.wikipedia.org/wiki/Music');
INSERT INTO HOBBY (name,description)  VALUES ('Podcasts','https://en.wikipedia.org/wiki/Podcasts');
INSERT INTO HOBBY (name,description)  VALUES ('Låseplukning','https://en.wikipedia.org/wiki/Lock_picking');
INSERT INTO HOBBY (name,description)  VALUES ('Bearbejdning','https://en.wikipedia.org/wiki/Machining');
INSERT INTO HOBBY (name,description)  VALUES ('Macrame','https://en.wikipedia.org/wiki/Macrame');
INSERT INTO HOBBY (name,description)  VALUES ('Magi (illusion)','https://en.wikipedia.org/wiki/Magic_(illusion)');
INSERT INTO HOBBY (name,description)  VALUES ('Makeup','https://en.wikipedia.org/wiki/Makeup');
INSERT INTO HOBBY (name,description)  VALUES ('Labyrint','https://en.wikipedia.org/wiki/Maze');
INSERT INTO HOBBY (name,description)  VALUES ('Metalbearbejdning','https://en.wikipedia.org/wiki/Metalworking');
INSERT INTO HOBBY (name,description)  VALUES ('Modelbygning','https://en.wikipedia.org/wiki/Model_building');
INSERT INTO HOBBY (name,description)  VALUES ('Model engineering','https://en.wikipedia.org/wiki/Model_engineering');
INSERT INTO HOBBY (name,description)  VALUES ('Negle kunst','https://en.wikipedia.org/wiki/Nail_art');
INSERT INTO HOBBY (name,description)  VALUES ('Nålepunkt','https://en.wikipedia.org/wiki/Needlepoint');
INSERT INTO HOBBY (name,description)  VALUES ('Origami','https://en.wikipedia.org/wiki/Origami');
INSERT INTO HOBBY (name,description)  VALUES ('Maleri','https://en.wikipedia.org/wiki/Painting');
INSERT INTO HOBBY (name,description)  VALUES ('Håndflade','https://en.wikipedia.org/wiki/Palmistry');
INSERT INTO HOBBY (name,description)  VALUES ('Adoption af kæledyr','https://en.wikipedia.org/wiki/Pet_adoption');
INSERT INTO HOBBY (name,description)  VALUES ('Filateli','https://en.wikipedia.org/wiki/Philately');
INSERT INTO HOBBY (name,description)  VALUES ('Fotografering','https://en.wikipedia.org/wiki/Photography');
INSERT INTO HOBBY (name,description)  VALUES ('Pilates','https://en.wikipedia.org/wiki/Pilates');
INSERT INTO HOBBY (name,description)  VALUES ('Poi (performance)','https://en.wikipedia.org/wiki/Poi_(performance_art)');
INSERT INTO HOBBY (name,description)  VALUES ('Pole Dancing (siden findes ikke)','https://en.wikipedia.org/w/index.php?title=Pole_Dancing&action=edit&redlink=1');
INSERT INTO HOBBY (name,description)  VALUES ('Keramik','https://en.wikipedia.org/wiki/Pottery');
INSERT INTO HOBBY (name,description)  VALUES ('Kraftløftning','https://en.wikipedia.org/wiki/Powerlifting');
INSERT INTO HOBBY (name,description)  VALUES ('Praktiske vittigheder','https://en.wikipedia.org/wiki/Practical_jokes');
INSERT INTO HOBBY (name,description)  VALUES ('Presset blomsterhåndværk','https://en.wikipedia.org/wiki/Pressed_flower_craft');
INSERT INTO HOBBY (name,description)  VALUES ('Gåde','https://en.wikipedia.org/wiki/Puzzle');
INSERT INTO HOBBY (name,description)  VALUES ('Quilling','https://en.wikipedia.org/wiki/Quilling');
INSERT INTO HOBBY (name,description)  VALUES ('Quiltning','https://en.wikipedia.org/wiki/Quilting');
INSERT INTO HOBBY (name,description)  VALUES ('Quizzer','https://en.wikipedia.org/wiki/Quizzes');
INSERT INTO HOBBY (name,description)  VALUES ('Radiostyret model','https://en.wikipedia.org/wiki/Radio-controlled_model');
INSERT INTO HOBBY (name,description)  VALUES ('Modellering af jernbanetransport','https://en.wikipedia.org/wiki/Rail_transport_modeling');
INSERT INTO HOBBY (name,description)  VALUES ('Rapping','https://en.wikipedia.org/wiki/Rapping');
INSERT INTO HOBBY (name,description)  VALUES ('Læsning','https://en.wikipedia.org/wiki/Reading');
INSERT INTO HOBBY (name,description)  VALUES ('Efterbehandling','https://en.wikipedia.org/wiki/Refinishing');
INSERT INTO HOBBY (name,description)  VALUES ('Reiki','https://en.wikipedia.org/wiki/Reiki');
INSERT INTO HOBBY (name,description)  VALUES ('Robotkamp','https://en.wikipedia.org/wiki/Robot_combat');
INSERT INTO HOBBY (name,description)  VALUES ('Rubiks terning','https://en.wikipedia.org/wiki/Rubik%27s_Cube');
INSERT INTO HOBBY (name,description)  VALUES ('Scrapbooking','https://en.wikipedia.org/wiki/Scrapbooking');
INSERT INTO HOBBY (name,description)  VALUES ('SCUBA Dykning','https://en.wikipedia.org/wiki/SCUBA_Diving');
INSERT INTO HOBBY (name,description)  VALUES ('Modellering','https://en.wikipedia.org/wiki/Sculpting');
INSERT INTO HOBBY (name,description)  VALUES ('Syning','https://en.wikipedia.org/wiki/Sewing');
INSERT INTO HOBBY (name,description)  VALUES ('Skomageri','https://en.wikipedia.org/wiki/Shoemaking');
INSERT INTO HOBBY (name,description)  VALUES ('Synger','https://en.wikipedia.org/wiki/Singing');
INSERT INTO HOBBY (name,description)  VALUES ('Skitse (tegning)','https://en.wikipedia.org/wiki/Sketch_(drawing)');
INSERT INTO HOBBY (name,description)  VALUES ('Sjippetov','https://en.wikipedia.org/wiki/Skipping_rope');
INSERT INTO HOBBY (name,description)  VALUES ('Slot bil','https://en.wikipedia.org/wiki/Slot_car');
INSERT INTO HOBBY (name,description)  VALUES ('Sæbefremstilling','https://en.wikipedia.org/wiki/Soapmaking');
INSERT INTO HOBBY (name,description)  VALUES ('Sociale medier','https://en.wikipedia.org/wiki/Social_media');
INSERT INTO HOBBY (name,description)  VALUES ('Regneark','https://en.wikipedia.org/wiki/Spreadsheets');
INSERT INTO HOBBY (name,description)  VALUES ('Stand-up','https://en.wikipedia.org/wiki/Stand-up_comedy');
INSERT INTO HOBBY (name,description)  VALUES ('Frimærkesamling','https://en.wikipedia.org/wiki/Stamp_collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Bordtennis','https://en.wikipedia.org/wiki/Table_tennis');
INSERT INTO HOBBY (name,description)  VALUES ('Tarot','https://en.wikipedia.org/wiki/Tarot');
INSERT INTO HOBBY (name,description)  VALUES ('Taksidermi','https://en.wikipedia.org/wiki/Taxidermy');
INSERT INTO HOBBY (name,description)  VALUES ('Velgørenhedsbutik','https://en.wikipedia.org/wiki/Charity_shop');
INSERT INTO HOBBY (name,description)  VALUES ('Videoredigering','https://en.wikipedia.org/wiki/Video_editing');
INSERT INTO HOBBY (name,description)  VALUES ('Udvikling af videospil','https://en.wikipedia.org/wiki/Video_game_development');
INSERT INTO HOBBY (name,description)  VALUES ('Videospil','https://en.wikipedia.org/wiki/Video_gaming');
INSERT INTO HOBBY (name,description)  VALUES ('Videografi','https://en.wikipedia.org/wiki/Videography');
INSERT INTO HOBBY (name,description)  VALUES ('Virtual reality','https://en.wikipedia.org/wiki/Virtual_reality');
INSERT INTO HOBBY (name,description)  VALUES ('Film','https://en.wikipedia.org/wiki/Movies');
INSERT INTO HOBBY (name,description)  VALUES ('Tv-program','https://en.wikipedia.org/wiki/Television_program');
INSERT INTO HOBBY (name,description)  VALUES ('Voksning','https://en.wikipedia.org/wiki/Waxing');
INSERT INTO HOBBY (name,description)  VALUES ('Vævning','https://en.wikipedia.org/wiki/Weaving');
INSERT INTO HOBBY (name,description)  VALUES ('Webtoon','https://en.wikipedia.org/wiki/Webtoon');
INSERT INTO HOBBY (name,description)  VALUES ('Vægt træning','https://en.wikipedia.org/wiki/Weight_training');
INSERT INTO HOBBY (name,description)  VALUES ('Svejsning','https://en.wikipedia.org/wiki/Welding');
INSERT INTO HOBBY (name,description)  VALUES ('Hviskende','https://en.wikipedia.org/wiki/Whittling');
INSERT INTO HOBBY (name,description)  VALUES ('Vinfremstilling','https://en.wikipedia.org/wiki/Winemaking');
INSERT INTO HOBBY (name,description)  VALUES ('Træskæring','https://en.wikipedia.org/wiki/Wood_carving');
INSERT INTO HOBBY (name,description)  VALUES ('Træbearbejdning','https://en.wikipedia.org/wiki/Woodworking');
INSERT INTO HOBBY (name,description)  VALUES ('Ordsøgninger','https://en.wikipedia.org/wiki/Word_searches');
INSERT INTO HOBBY (name,description)  VALUES ('Verdensbygning','https://en.wikipedia.org/wiki/Worldbuilding');
INSERT INTO HOBBY (name,description)  VALUES ('Skrivning','https://en.wikipedia.org/wiki/Writing');
INSERT INTO HOBBY (name,description)  VALUES ('Yo-yoing','https://en.wikipedia.org/wiki/Yo-yoing');
INSERT INTO HOBBY (name,description)  VALUES ('Yoga','https://en.wikipedia.org/wiki/Yoga');
INSERT INTO HOBBY (name,description)  VALUES ('Zumba','https://en.wikipedia.org/wiki/Zumba');
INSERT INTO HOBBY (name,description)  VALUES ('Luftsport','https://en.wikipedia.org/wiki/Air_sports');
INSERT INTO HOBBY (name,description)  VALUES ('Airsoft','https://en.wikipedia.org/wiki/Airsoft');
INSERT INTO HOBBY (name,description)  VALUES ('Amatørgeologi','https://en.wikipedia.org/wiki/Amateur_geology');
INSERT INTO HOBBY (name,description)  VALUES ('Forlystelsespark','https://en.wikipedia.org/wiki/Amusement_park');
INSERT INTO HOBBY (name,description)  VALUES ('Bueskydning','https://en.wikipedia.org/wiki/Archery');
INSERT INTO HOBBY (name,description)  VALUES ('Astronomi','https://en.wikipedia.org/wiki/Astronomy');
INSERT INTO HOBBY (name,description)  VALUES ('Backpacking (vildmark)','https://en.wikipedia.org/wiki/Backpacking_(wilderness)');
INSERT INTO HOBBY (name,description)  VALUES ('Badminton','https://en.wikipedia.org/wiki/Badminton');
INSERT INTO HOBBY (name,description)  VALUES ('Base jumping','https://en.wikipedia.org/wiki/BASE_jumping');
INSERT INTO HOBBY (name,description)  VALUES ('Baseball','https://en.wikipedia.org/wiki/Baseball');
INSERT INTO HOBBY (name,description)  VALUES ('Basketball','https://en.wikipedia.org/wiki/Basketball');
INSERT INTO HOBBY (name,description)  VALUES ('Biavl','https://en.wikipedia.org/wiki/Beekeeping');
INSERT INTO HOBBY (name,description)  VALUES ('Fuglekiggeri','https://en.wikipedia.org/wiki/Birdwatching');
INSERT INTO HOBBY (name,description)  VALUES ('Smedarbejde','https://en.wikipedia.org/wiki/Blacksmithing');
INSERT INTO HOBBY (name,description)  VALUES ('BMX','https://en.wikipedia.org/wiki/BMX');
INSERT INTO HOBBY (name,description)  VALUES ('Brætsport','https://en.wikipedia.org/wiki/Board_sports');
INSERT INTO HOBBY (name,description)  VALUES ('Bodybuilding','https://en.wikipedia.org/wiki/Bodybuilding');
INSERT INTO HOBBY (name,description)  VALUES ('Bonsai','https://en.wikipedia.org/wiki/Bonsai');
INSERT INTO HOBBY (name,description)  VALUES ('Sommerfugletur','https://en.wikipedia.org/wiki/Butterfly_watching');
INSERT INTO HOBBY (name,description)  VALUES ('Bus','https://en.wikipedia.org/wiki/Bus');
INSERT INTO HOBBY (name,description)  VALUES ('Camping','https://en.wikipedia.org/wiki/Camping');
INSERT INTO HOBBY (name,description)  VALUES ('Kanosejlads','https://en.wikipedia.org/wiki/Canoeing');
INSERT INTO HOBBY (name,description)  VALUES ('Canyoning','https://en.wikipedia.org/wiki/Canyoning');
INSERT INTO HOBBY (name,description)  VALUES ('Huleforskning','https://en.wikipedia.org/wiki/Caving');
INSERT INTO HOBBY (name,description)  VALUES ('Kompostering','https://en.wikipedia.org/wiki/Composting');
INSERT INTO HOBBY (name,description)  VALUES ('Cykling','https://en.wikipedia.org/wiki/Cycling');
INSERT INTO HOBBY (name,description)  VALUES ('Dowsing','https://en.wikipedia.org/wiki/Dowsing');
INSERT INTO HOBBY (name,description)  VALUES ('Kørsel','https://en.wikipedia.org/wiki/Driving');
INSERT INTO HOBBY (name,description)  VALUES ('Landbrug','https://en.wikipedia.org/wiki/Farming');
INSERT INTO HOBBY (name,description)  VALUES ('Fiskeri','https://en.wikipedia.org/wiki/Fishing');
INSERT INTO HOBBY (name,description)  VALUES ('Flag fodbold','https://en.wikipedia.org/wiki/Flag_football');
INSERT INTO HOBBY (name,description)  VALUES ('Blomst','https://en.wikipedia.org/wiki/Flower');
INSERT INTO HOBBY (name,description)  VALUES ('Luftfart','https://en.wikipedia.org/wiki/Aviation');
INSERT INTO HOBBY (name,description)  VALUES ('Flyvende skive','https://en.wikipedia.org/wiki/Flying_disc');
INSERT INTO HOBBY (name,description)  VALUES ('Foder','https://en.wikipedia.org/wiki/Foraging');
INSERT INTO HOBBY (name,description)  VALUES ('Fossicking','https://en.wikipedia.org/wiki/Fossicking');
INSERT INTO HOBBY (name,description)  VALUES ('Freestyle fodbold','https://en.wikipedia.org/wiki/Freestyle_football');
INSERT INTO HOBBY (name,description)  VALUES ('Havearbejde','https://en.wikipedia.org/wiki/Gardening');
INSERT INTO HOBBY (name,description)  VALUES ('Geocaching','https://en.wikipedia.org/wiki/Geocaching');
INSERT INTO HOBBY (name,description)  VALUES ('Spøgelsesjagt','https://en.wikipedia.org/wiki/Ghost_hunting');
INSERT INTO HOBBY (name,description)  VALUES ('Guldprospektering','https://en.wikipedia.org/wiki/Gold_prospecting');
INSERT INTO HOBBY (name,description)  VALUES ('Graffiti','https://en.wikipedia.org/wiki/Graffiti');
INSERT INTO HOBBY (name,description)  VALUES ('Håndbold','https://en.wikipedia.org/wiki/Handball');
INSERT INTO HOBBY (name,description)  VALUES ('Naturlægemidler','https://en.wikipedia.org/wiki/Herbalism');
INSERT INTO HOBBY (name,description)  VALUES ('Herping','https://en.wikipedia.org/wiki/Herping');
INSERT INTO HOBBY (name,description)  VALUES ('Højeffektiv raket','https://en.wikipedia.org/wiki/High-power_rocketry');
INSERT INTO HOBBY (name,description)  VALUES ('Vandreture','https://en.wikipedia.org/wiki/Hiking');
INSERT INTO HOBBY (name,description)  VALUES ('Hobby hest','https://en.wikipedia.org/wiki/Hobby_horse');
INSERT INTO HOBBY (name,description)  VALUES ('Hobby tunneling','https://en.wikipedia.org/wiki/Hobby_tunneling');
INSERT INTO HOBBY (name,description)  VALUES ('Hooping','https://en.wikipedia.org/wiki/Hooping');
INSERT INTO HOBBY (name,description)  VALUES ('Ridning','https://en.wikipedia.org/wiki/Horseback_riding');
INSERT INTO HOBBY (name,description)  VALUES ('Jagt','https://en.wikipedia.org/wiki/Hunting');
INSERT INTO HOBBY (name,description)  VALUES ('In-line skating','https://en.wikipedia.org/wiki/Inline_skating');
INSERT INTO HOBBY (name,description)  VALUES ('Løbe','https://en.wikipedia.org/wiki/Jogging');
INSERT INTO HOBBY (name,description)  VALUES ('Ro kajak','https://en.wikipedia.org/wiki/Kayaking');
INSERT INTO HOBBY (name,description)  VALUES ('Glente','https://en.wikipedia.org/wiki/Kite');
INSERT INTO HOBBY (name,description)  VALUES ('Kitesurfing','https://en.wikipedia.org/wiki/Kitesurfing');
INSERT INTO HOBBY (name,description)  VALUES ('Lacrosse','https://en.wikipedia.org/wiki/Lacrosse');
INSERT INTO HOBBY (name,description)  VALUES ('LARPing','https://en.wikipedia.org/wiki/LARPing');
INSERT INTO HOBBY (name,description)  VALUES ('Letterboxing (hobby)','https://en.wikipedia.org/wiki/Letterboxing_(hobby)');
INSERT INTO HOBBY (name,description)  VALUES ('Longboarding','https://en.wikipedia.org/wiki/Longboarding');
INSERT INTO HOBBY (name,description)  VALUES ('Kampsport','https://en.wikipedia.org/wiki/Martial_arts');
INSERT INTO HOBBY (name,description)  VALUES ('Metaldetektor','https://en.wikipedia.org/wiki/Metal_detector');
INSERT INTO HOBBY (name,description)  VALUES ('Meteorologi','https://en.wikipedia.org/wiki/Meteorology');
INSERT INTO HOBBY (name,description)  VALUES ('Motorsport','https://en.wikipedia.org/wiki/Motor_sports');
INSERT INTO HOBBY (name,description)  VALUES ('Mountainbiking','https://en.wikipedia.org/wiki/Mountain_biking');
INSERT INTO HOBBY (name,description)  VALUES ('Bjergbestigning','https://en.wikipedia.org/wiki/Mountaineering');
INSERT INTO HOBBY (name,description)  VALUES ('Museum','https://en.wikipedia.org/wiki/Museum');
INSERT INTO HOBBY (name,description)  VALUES ('Svampejagt','https://en.wikipedia.org/wiki/Mushroom_hunting');
INSERT INTO HOBBY (name,description)  VALUES ('Mykologi','https://en.wikipedia.org/wiki/Mycology');
INSERT INTO HOBBY (name,description)  VALUES ('Netball','https://en.wikipedia.org/wiki/Netball');
INSERT INTO HOBBY (name,description)  VALUES ('Nordisk skøjteløb','https://en.wikipedia.org/wiki/Nordic_skating');
INSERT INTO HOBBY (name,description)  VALUES ('Orientering','https://en.wikipedia.org/wiki/Orienteering');
INSERT INTO HOBBY (name,description)  VALUES ('Paintball','https://en.wikipedia.org/wiki/Paintball');
INSERT INTO HOBBY (name,description)  VALUES ('Parkour','https://en.wikipedia.org/wiki/Parkour');
INSERT INTO HOBBY (name,description)  VALUES ('Podcast','https://en.wikipedia.org/wiki/Podcast');
INSERT INTO HOBBY (name,description)  VALUES ('Polo','https://en.wikipedia.org/wiki/Polo');
INSERT INTO HOBBY (name,description)  VALUES ('Offentlig transport','https://en.wikipedia.org/wiki/Public_transport');
INSERT INTO HOBBY (name,description)  VALUES ('Rafting','https://en.wikipedia.org/wiki/Rafting');
INSERT INTO HOBBY (name,description)  VALUES ('Jernbane','https://en.wikipedia.org/wiki/Railway');
INSERT INTO HOBBY (name,description)  VALUES ('Rappellering','https://en.wikipedia.org/wiki/Rappelling');
INSERT INTO HOBBY (name,description)  VALUES ('Road Cykling','https://en.wikipedia.org/wiki/Road_Cycling');
INSERT INTO HOBBY (name,description)  VALUES ('Rulleskøjteløb','https://en.wikipedia.org/wiki/Roller_skating');
INSERT INTO HOBBY (name,description)  VALUES ('Rugby fodbold','https://en.wikipedia.org/wiki/Rugby_football');
INSERT INTO HOBBY (name,description)  VALUES ('Løb','https://en.wikipedia.org/wiki/Running');
INSERT INTO HOBBY (name,description)  VALUES ('Sejler','https://en.wikipedia.org/wiki/Sailing');
INSERT INTO HOBBY (name,description)  VALUES ('Sand kunst og leg','https://en.wikipedia.org/wiki/Sand_art_and_play');
INSERT INTO HOBBY (name,description)  VALUES ('Spejder','https://en.wikipedia.org/wiki/Scouting');
INSERT INTO HOBBY (name,description)  VALUES ('Dykning','https://en.wikipedia.org/wiki/Scuba_diving');
INSERT INTO HOBBY (name,description)  VALUES ('Sculling','https://en.wikipedia.org/wiki/Sculling');
INSERT INTO HOBBY (name,description)  VALUES ('Roning (sport)','https://en.wikipedia.org/wiki/Rowing_(sport)');
INSERT INTO HOBBY (name,description)  VALUES ('Optagelse','https://en.wikipedia.org/wiki/Shooting');
INSERT INTO HOBBY (name,description)  VALUES ('Handle ind','https://en.wikipedia.org/wiki/Shopping');
INSERT INTO HOBBY (name,description)  VALUES ('Shuffleboard','https://en.wikipedia.org/wiki/Shuffleboard');
INSERT INTO HOBBY (name,description)  VALUES ('Skateboarding','https://en.wikipedia.org/wiki/Skateboarding');
INSERT INTO HOBBY (name,description)  VALUES ('Stå på ski','https://en.wikipedia.org/wiki/Skiing');
INSERT INTO HOBBY (name,description)  VALUES ('Skimboarding','https://en.wikipedia.org/wiki/Skimboarding');
INSERT INTO HOBBY (name,description)  VALUES ('Faldskærmsudspring','https://en.wikipedia.org/wiki/Skydiving');
INSERT INTO HOBBY (name,description)  VALUES ('Slacklining','https://en.wikipedia.org/wiki/Slacklining');
INSERT INTO HOBBY (name,description)  VALUES ('Snowboarding','https://en.wikipedia.org/wiki/Snowboarding');
INSERT INTO HOBBY (name,description)  VALUES ('Snescooterkørsel','https://en.wikipedia.org/wiki/Snowmobiling');
INSERT INTO HOBBY (name,description)  VALUES ('Snesko','https://en.wikipedia.org/wiki/Snowshoeing');
INSERT INTO HOBBY (name,description)  VALUES ('Fodbold','https://en.wikipedia.org/wiki/Soccer');
INSERT INTO HOBBY (name,description)  VALUES ('Sten springer over','https://en.wikipedia.org/wiki/Stone_skipping');
INSERT INTO HOBBY (name,description)  VALUES ('Solbadning','https://en.wikipedia.org/wiki/Sun_bathing');
INSERT INTO HOBBY (name,description)  VALUES ('Surfing','https://en.wikipedia.org/wiki/Surfing');
INSERT INTO HOBBY (name,description)  VALUES ('Overlevelse','https://en.wikipedia.org/wiki/Survivalism');
INSERT INTO HOBBY (name,description)  VALUES ('Menneskelig svømning','https://en.wikipedia.org/wiki/Human_swimming');
INSERT INTO HOBBY (name,description)  VALUES ('Taekwondo','https://en.wikipedia.org/wiki/Taekwondo');
INSERT INTO HOBBY (name,description)  VALUES ('Tai Chi','https://en.wikipedia.org/wiki/Tai_chi');
INSERT INTO HOBBY (name,description)  VALUES ('Tennis','https://en.wikipedia.org/wiki/Tennis');
INSERT INTO HOBBY (name,description)  VALUES ('Topiary','https://en.wikipedia.org/wiki/Topiary');
INSERT INTO HOBBY (name,description)  VALUES ('Turisme','https://en.wikipedia.org/wiki/Tourism');
INSERT INTO HOBBY (name,description)  VALUES ('Gennem vandring','https://en.wikipedia.org/wiki/Thru-hiking');
INSERT INTO HOBBY (name,description)  VALUES ('Messe','https://en.wikipedia.org/wiki/Trade_fair');
INSERT INTO HOBBY (name,description)  VALUES ('Rejse','https://en.wikipedia.org/wiki/Travel');
INSERT INTO HOBBY (name,description)  VALUES ('Byudforskning','https://en.wikipedia.org/wiki/Urban_exploration');
INSERT INTO HOBBY (name,description)  VALUES ('Ferie','https://en.wikipedia.org/wiki/Vacation');
INSERT INTO HOBBY (name,description)  VALUES ('Vegetabilsk landbrug','https://en.wikipedia.org/wiki/Vegetable_farming');
INSERT INTO HOBBY (name,description)  VALUES ('Restaurering af køretøjet','https://en.wikipedia.org/wiki/Vehicle_restoration');
INSERT INTO HOBBY (name,description)  VALUES ('Gå','https://en.wikipedia.org/wiki/Walking');
INSERT INTO HOBBY (name,description)  VALUES ('Vandsport','https://en.wikipedia.org/wiki/Water_sports');
INSERT INTO HOBBY (name,description)  VALUES ('Biologi','https://en.wikipedia.org/wiki/Biology');
INSERT INTO HOBBY (name,description)  VALUES ('Kemi','https://en.wikipedia.org/wiki/Chemistry');
INSERT INTO HOBBY (name,description)  VALUES ('Elektrokemi','https://en.wikipedia.org/wiki/Electrochemistry');
INSERT INTO HOBBY (name,description)  VALUES ('Geografi','https://en.wikipedia.org/wiki/Geography');
INSERT INTO HOBBY (name,description)  VALUES ('Historie','https://en.wikipedia.org/wiki/History');
INSERT INTO HOBBY (name,description)  VALUES ('Matematik','https://en.wikipedia.org/wiki/Mathematics');
INSERT INTO HOBBY (name,description)  VALUES ('Psykologi','https://en.wikipedia.org/wiki/Psychology');
INSERT INTO HOBBY (name,description)  VALUES ('Fysik','https://en.wikipedia.org/wiki/Physics');
INSERT INTO HOBBY (name,description)  VALUES ('Jernbanetransport','https://en.wikipedia.org/wiki/Rail_transport');
INSERT INTO HOBBY (name,description)  VALUES ('Videnskab og teknologi studier','https://en.wikipedia.org/wiki/Science_and_technology_studies');
INSERT INTO HOBBY (name,description)  VALUES ('Sociale Studier','https://en.wikipedia.org/wiki/Social_studies');
INSERT INTO HOBBY (name,description)  VALUES ('Sportsvidenskab','https://en.wikipedia.org/wiki/Sports_science');
INSERT INTO HOBBY (name,description)  VALUES ('Action figur','https://en.wikipedia.org/wiki/Action_figure');
INSERT INTO HOBBY (name,description)  VALUES ('Antikviteter','https://en.wikipedia.org/wiki/Antiquing');
INSERT INTO HOBBY (name,description)  VALUES ('Ant-holder','https://en.wikipedia.org/wiki/Ant-keeping');
INSERT INTO HOBBY (name,description)  VALUES ('Kunstindsamling','https://en.wikipedia.org/wiki/Art_collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Bogindsamling','https://en.wikipedia.org/wiki/Book_collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Knapopsamling','https://en.wikipedia.org/wiki/Button_collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Bytte kort','https://en.wikipedia.org/wiki/Trading_cards');
INSERT INTO HOBBY (name,description)  VALUES ('Møntindsamling','https://en.wikipedia.org/wiki/Coin_collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Tegneserieindsamling','https://en.wikipedia.org/wiki/Comic_book_collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Deltiologi','https://en.wikipedia.org/wiki/Deltiology');
INSERT INTO HOBBY (name,description)  VALUES ('Die-cast legetøj','https://en.wikipedia.org/wiki/Die-cast_toy');
INSERT INTO HOBBY (name,description)  VALUES ('Digital hamstring','https://en.wikipedia.org/wiki/Digital_hoarding');
INSERT INTO HOBBY (name,description)  VALUES ('Dukker','https://en.wikipedia.org/wiki/Dolls');
INSERT INTO HOBBY (name,description)  VALUES ('Elementindsamling','https://en.wikipedia.org/wiki/Element_collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Flygtig','https://en.wikipedia.org/wiki/Ephemera');
INSERT INTO HOBBY (name,description)  VALUES ('Telefonkort','https://en.wikipedia.org/wiki/Telephone_card');
INSERT INTO HOBBY (name,description)  VALUES ('Knivopsamling','https://en.wikipedia.org/wiki/Knife_collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Lotologi','https://en.wikipedia.org/wiki/Lotology');
INSERT INTO HOBBY (name,description)  VALUES ('Film memorabilia','https://en.wikipedia.org/wiki/Film_memorabilia');
INSERT INTO HOBBY (name,description)  VALUES ('Fingeraftryk','https://en.wikipedia.org/wiki/Fingerprint');
INSERT INTO HOBBY (name,description)  VALUES ('Parfume','https://en.wikipedia.org/wiki/Perfume');
INSERT INTO HOBBY (name,description)  VALUES ('Phillumeny','https://en.wikipedia.org/wiki/Phillumeny');
INSERT INTO HOBBY (name,description)  VALUES ('Pladesamling','https://en.wikipedia.org/wiki/Record_collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Rock tumbling','https://en.wikipedia.org/wiki/Rock_tumbling');
INSERT INTO HOBBY (name,description)  VALUES ('Patch indsamling','https://en.wikipedia.org/wiki/Patch_collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Sko','https://en.wikipedia.org/wiki/Shoes');
INSERT INTO HOBBY (name,description)  VALUES ('Sportsmemorabilia','https://en.wikipedia.org/wiki/Sports_memorabilia');
INSERT INTO HOBBY (name,description)  VALUES ('Tøjdyr','https://en.wikipedia.org/wiki/Stuffed_toy');
INSERT INTO HOBBY (name,description)  VALUES ('Te pose','https://en.wikipedia.org/wiki/Tea_bag');
INSERT INTO HOBBY (name,description)  VALUES ('Billet (adgang)','https://en.wikipedia.org/wiki/Ticket_(admission)');
INSERT INTO HOBBY (name,description)  VALUES ('Legetøj','https://en.wikipedia.org/wiki/Toys');
INSERT INTO HOBBY (name,description)  VALUES ('Transitkort','https://en.wikipedia.org/wiki/Transit_map');
INSERT INTO HOBBY (name,description)  VALUES ('Samling af videospil','https://en.wikipedia.org/wiki/Video_game_collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Vintage biler','https://en.wikipedia.org/wiki/Vintage_cars');
INSERT INTO HOBBY (name,description)  VALUES ('Vintage tøj','https://en.wikipedia.org/wiki/Vintage_clothing');
INSERT INTO HOBBY (name,description)  VALUES ('Vinylplader','https://en.wikipedia.org/wiki/Vinyl_Records');
INSERT INTO HOBBY (name,description)  VALUES ('Auto audiophilia','https://en.wikipedia.org/wiki/Auto_audiophilia');
INSERT INTO HOBBY (name,description)  VALUES ('Fossil jagt','https://en.wikipedia.org/wiki/Fossil_hunting');
INSERT INTO HOBBY (name,description)  VALUES ('Insektindsamling','https://en.wikipedia.org/wiki/Insect_collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Magnetfiskeri','https://en.wikipedia.org/wiki/Magnet_fishing');
INSERT INTO HOBBY (name,description)  VALUES ('Metaldetektering','https://en.wikipedia.org/wiki/Metal_detecting');
INSERT INTO HOBBY (name,description)  VALUES ('Mineralindsamling','https://en.wikipedia.org/wiki/Mineral_collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Stenbalancering','https://en.wikipedia.org/wiki/Rock_balancing');
INSERT INTO HOBBY (name,description)  VALUES ('Havglas','https://en.wikipedia.org/wiki/Sea_glass');
INSERT INTO HOBBY (name,description)  VALUES ('Muslingeskal','https://en.wikipedia.org/wiki/Seashell');
INSERT INTO HOBBY (name,description)  VALUES ('Stenopsamling','https://en.wikipedia.org/wiki/Stone_collecting');
INSERT INTO HOBBY (name,description)  VALUES ('Dyrepleje','https://en.wikipedia.org/wiki/Animal_fancy');
INSERT INTO HOBBY (name,description)  VALUES ('Øksekast','https://en.wikipedia.org/wiki/Axe_throwing');
INSERT INTO HOBBY (name,description)  VALUES ('Backgammon','https://en.wikipedia.org/wiki/Backgammon');
INSERT INTO HOBBY (name,description)  VALUES ('Skønhedskonkurrence','https://en.wikipedia.org/wiki/Beauty_pageant');
INSERT INTO HOBBY (name,description)  VALUES ('Boksning','https://en.wikipedia.org/wiki/Boxing');
INSERT INTO HOBBY (name,description)  VALUES ('Kontraktsbro','https://en.wikipedia.org/wiki/Contract_Bridge');
INSERT INTO HOBBY (name,description)  VALUES ('Kladder','https://en.wikipedia.org/wiki/Draughts');
INSERT INTO HOBBY (name,description)  VALUES ('Cheerleading','https://en.wikipedia.org/wiki/Cheerleading');
INSERT INTO HOBBY (name,description)  VALUES ('Skak','https://en.wikipedia.org/wiki/Chess');
INSERT INTO HOBBY (name,description)  VALUES ('Farvebeskyttelse (flag spinding)','https://en.wikipedia.org/wiki/Color_guard_(flag_spinning)');
INSERT INTO HOBBY (name,description)  VALUES ('Cribbage','https://en.wikipedia.org/wiki/Cribbage');
INSERT INTO HOBBY (name,description)  VALUES ('Curling','https://en.wikipedia.org/wiki/Curling');
INSERT INTO HOBBY (name,description)  VALUES ('Konkurrencedygtig dans','https://en.wikipedia.org/wiki/Competitive_dance');
INSERT INTO HOBBY (name,description)  VALUES ('Dart','https://en.wikipedia.org/wiki/Darts');
INSERT INTO HOBBY (name,description)  VALUES ('Debat','https://en.wikipedia.org/wiki/Debate');
INSERT INTO HOBBY (name,description)  VALUES ('Dominoer','https://en.wikipedia.org/wiki/Dominoes');
INSERT INTO HOBBY (name,description)  VALUES ('Konkurrencedygtig spisning','https://en.wikipedia.org/wiki/Competitive_eating');
INSERT INTO HOBBY (name,description)  VALUES ('Esports','https://en.wikipedia.org/wiki/Esports');
INSERT INTO HOBBY (name,description)  VALUES ('Hegn','https://en.wikipedia.org/wiki/Fencing');
INSERT INTO HOBBY (name,description)  VALUES ('Gå (spil)','https://en.wikipedia.org/wiki/Go_(game)');
INSERT INTO HOBBY (name,description)  VALUES ('Ishockey','https://en.wikipedia.org/wiki/Ice_hockey');
INSERT INTO HOBBY (name,description)  VALUES ('Judo','https://en.wikipedia.org/wiki/Judo');
INSERT INTO HOBBY (name,description)  VALUES ('Jujitsu','https://en.wikipedia.org/wiki/Jujitsu');
INSERT INTO HOBBY (name,description)  VALUES ('Kabaddi','https://en.wikipedia.org/wiki/Kabaddi');
INSERT INTO HOBBY (name,description)  VALUES ('Ordspil','https://en.wikipedia.org/wiki/Word_games');
INSERT INTO HOBBY (name,description)  VALUES ('Lasermærke','https://en.wikipedia.org/wiki/Laser_tag');
INSERT INTO HOBBY (name,description)  VALUES ('Mahjong','https://en.wikipedia.org/wiki/Mahjong');
INSERT INTO HOBBY (name,description)  VALUES ('Kugler','https://en.wikipedia.org/wiki/Marbles');
INSERT INTO HOBBY (name,description)  VALUES ('Model FN','https://en.wikipedia.org/wiki/Model_United_Nations');
INSERT INTO HOBBY (name,description)  VALUES ('Poker','https://en.wikipedia.org/wiki/Poker');
INSERT INTO HOBBY (name,description)  VALUES ('Pool (cue sports)','https://en.wikipedia.org/wiki/Pool_(cue_sports)');
INSERT INTO HOBBY (name,description)  VALUES ('Shogi','https://en.wikipedia.org/wiki/Shogi');
INSERT INTO HOBBY (name,description)  VALUES ('Slot bilspil','https://en.wikipedia.org/wiki/Slot_car_racing');
INSERT INTO HOBBY (name,description)  VALUES ('Hurtigkubning','https://en.wikipedia.org/wiki/Speedcubing');
INSERT INTO HOBBY (name,description)  VALUES ('Sport stabling','https://en.wikipedia.org/wiki/Sport_stacking');
INSERT INTO HOBBY (name,description)  VALUES ('Bordfodbold','https://en.wikipedia.org/wiki/Table_football');
INSERT INTO HOBBY (name,description)  VALUES ('Volleyball','https://en.wikipedia.org/wiki/Volleyball');
INSERT INTO HOBBY (name,description)  VALUES ('Brydning','https://en.wikipedia.org/wiki/Wrestling');
INSERT INTO HOBBY (name,description)  VALUES ('Association fodbold','https://en.wikipedia.org/wiki/Association_football');
INSERT INTO HOBBY (name,description)  VALUES ('Australsk spiller fodbold','https://en.wikipedia.org/wiki/Australian_rules_football');
INSERT INTO HOBBY (name,description)  VALUES ('Bilsport','https://en.wikipedia.org/wiki/Auto_racing');
INSERT INTO HOBBY (name,description)  VALUES ('Beach Volleyball','https://en.wikipedia.org/wiki/Beach_volleyball');
INSERT INTO HOBBY (name,description)  VALUES ('Breakdancing','https://en.wikipedia.org/wiki/Breakdancing');
INSERT INTO HOBBY (name,description)  VALUES ('Klatring','https://en.wikipedia.org/wiki/Climbing');
INSERT INTO HOBBY (name,description)  VALUES ('Cricket','https://en.wikipedia.org/wiki/Cricket');
INSERT INTO HOBBY (name,description)  VALUES ('Croquet','https://en.wikipedia.org/wiki/Croquet');
INSERT INTO HOBBY (name,description)  VALUES ('Disc golf','https://en.wikipedia.org/wiki/Disc_golf');
INSERT INTO HOBBY (name,description)  VALUES ('Hundesport','https://en.wikipedia.org/wiki/Dog_sport');
INSERT INTO HOBBY (name,description)  VALUES ('Udstillingsøvelse','https://en.wikipedia.org/wiki/Exhibition_drill');
INSERT INTO HOBBY (name,description)  VALUES ('Field hockey','https://en.wikipedia.org/wiki/Field_hockey');
INSERT INTO HOBBY (name,description)  VALUES ('Kunstskøjteløb','https://en.wikipedia.org/wiki/Figure_skating');
INSERT INTO HOBBY (name,description)  VALUES ('Fodtaske','https://en.wikipedia.org/wiki/Footbag');
INSERT INTO HOBBY (name,description)  VALUES ('Frisbee','https://en.wikipedia.org/wiki/Frisbee');
INSERT INTO HOBBY (name,description)  VALUES ('Golf','https://en.wikipedia.org/wiki/Golf');
INSERT INTO HOBBY (name,description)  VALUES ('Hestesko','https://en.wikipedia.org/wiki/Horseshoes');
INSERT INTO HOBBY (name,description)  VALUES ('Isbåd','https://en.wikipedia.org/wiki/Iceboat');
INSERT INTO HOBBY (name,description)  VALUES ('Jukskei','https://en.wikipedia.org/wiki/Jukskei');
INSERT INTO HOBBY (name,description)  VALUES ('Kart racing','https://en.wikipedia.org/wiki/Kart_racing');
INSERT INTO HOBBY (name,description)  VALUES ('Knivkastning','https://en.wikipedia.org/wiki/Knife_throwing');
INSERT INTO HOBBY (name,description)  VALUES ('Langdistanceløb','https://en.wikipedia.org/wiki/Long-distance_running');
INSERT INTO HOBBY (name,description)  VALUES ('Marcherende band','https://en.wikipedia.org/wiki/Marching_band');
INSERT INTO HOBBY (name,description)  VALUES ('Modelfly','https://en.wikipedia.org/wiki/Model_aircraft');
INSERT INTO HOBBY (name,description)  VALUES ('Pickleball','https://en.wikipedia.org/wiki/Pickleball');
INSERT INTO HOBBY (name,description)  VALUES ('Quidditch (sport)','https://en.wikipedia.org/wiki/Quidditch_(sport)');
INSERT INTO HOBBY (name,description)  VALUES ('Race gåtur','https://en.wikipedia.org/wiki/Race_walking');
INSERT INTO HOBBY (name,description)  VALUES ('Racquetball','https://en.wikipedia.org/wiki/Racquetball');
INSERT INTO HOBBY (name,description)  VALUES ('Radiostyret bil','https://en.wikipedia.org/wiki/Radio-controlled_car');
INSERT INTO HOBBY (name,description)  VALUES ('Roller derby','https://en.wikipedia.org/wiki/Roller_derby');
INSERT INTO HOBBY (name,description)  VALUES ('Rugby liga','https://en.wikipedia.org/wiki/Rugby_league');
INSERT INTO HOBBY (name,description)  VALUES ('Roning','https://en.wikipedia.org/wiki/Rowing');
INSERT INTO HOBBY (name,description)  VALUES ('Skydesport','https://en.wikipedia.org/wiki/Shooting_sport');
INSERT INTO HOBBY (name,description)  VALUES ('Slædehundevæddeløb','https://en.wikipedia.org/wiki/Sled_dog_racing');
INSERT INTO HOBBY (name,description)  VALUES ('Softball','https://en.wikipedia.org/wiki/Softball');
INSERT INTO HOBBY (name,description)  VALUES ('Hurtigløb på skøjter','https://en.wikipedia.org/wiki/Speed_skating');
INSERT INTO HOBBY (name,description)  VALUES ('Squash (sport)','https://en.wikipedia.org/wiki/Squash_(sport)');
INSERT INTO HOBBY (name,description)  VALUES ('Tennispolo','https://en.wikipedia.org/wiki/Tennis_polo');
INSERT INTO HOBBY (name,description)  VALUES ('Fastgør bil','https://en.wikipedia.org/wiki/Tether_car');
INSERT INTO HOBBY (name,description)  VALUES ('Tour skøjteløb','https://en.wikipedia.org/wiki/Tour_skating');
INSERT INTO HOBBY (name,description)  VALUES ('Trapshooting','https://en.wikipedia.org/wiki/Trapshooting');
INSERT INTO HOBBY (name,description)  VALUES ('Triatlon','https://en.wikipedia.org/wiki/Triathlon');
INSERT INTO HOBBY (name,description)  VALUES ('Ultimate (sport)','https://en.wikipedia.org/wiki/Ultimate_(sport)');
INSERT INTO HOBBY (name,description)  VALUES ('Vandpolo','https://en.wikipedia.org/wiki/Water_polo');
INSERT INTO HOBBY (name,description)  VALUES ('Læring','https://en.wikipedia.org/wiki/Learning');
INSERT INTO HOBBY (name,description)  VALUES ('Meditation','https://en.wikipedia.org/wiki/Meditation');
INSERT INTO HOBBY (name,description)  VALUES ('Mikroskopi','https://en.wikipedia.org/wiki/Microscopy');
INSERT INTO HOBBY (name,description)  VALUES ('Forskning','https://en.wikipedia.org/wiki/Research');
INSERT INTO HOBBY (name,description)  VALUES ('Kortbølgelytning','https://en.wikipedia.org/wiki/Shortwave_listening');
INSERT INTO HOBBY (name,description)  VALUES ('Audiofil','https://en.wikipedia.org/wiki/Audiophile');
INSERT INTO HOBBY (name,description)  VALUES ('Flyspotting','https://en.wikipedia.org/wiki/Aircraft_spotting');
INSERT INTO HOBBY (name,description)  VALUES ('Amatør astronomi','https://en.wikipedia.org/wiki/Amateur_astronomy');
INSERT INTO HOBBY (name,description)  VALUES ('Bus spotting','https://en.wikipedia.org/wiki/Bus_spotting');
INSERT INTO HOBBY (name,description)  VALUES ('Gongoozler','https://en.wikipedia.org/wiki/Gongoozler');
INSERT INTO HOBBY (name,description)  VALUES ('Satellitovervågning','https://en.wikipedia.org/wiki/Satellite_watching');
INSERT INTO HOBBY (name,description)  VALUES ('Trainspotting (hobby)','https://en.wikipedia.org/wiki/Trainspotting_(hobby)');
INSERT INTO HOBBY (name,description)  VALUES ('Hvalsafari','https://en.wikipedia.org/wiki/Whale_watching');
