 insert into cityinfo (zipcode,city) VALUES ('0555','Scanning');
 insert into cityinfo (zipcode,city) VALUES ('0800','Høje Taastrup');
 insert into cityinfo (zipcode,city) VALUES ('0877','København C');
 insert into cityinfo (zipcode,city) VALUES ('0892','Sjælland USF P');
 insert into cityinfo (zipcode,city) VALUES ('0893','Sjælland USF B');
 insert into cityinfo (zipcode,city) VALUES ('0894','Udbetaling');
 insert into cityinfo (zipcode,city) VALUES ('0897','eBrevsprækken');
 insert into cityinfo (zipcode,city) VALUES ('0899','Kommuneservice');
 insert into cityinfo (zipcode,city) VALUES ('0900','København C');
 insert into cityinfo (zipcode,city) VALUES ('0910','København C');
 insert into cityinfo (zipcode,city) VALUES ('0917','Københavns Pakkecenter');
 insert into cityinfo (zipcode,city) VALUES ('0918','Københavns Pakke BRC');
 insert into cityinfo (zipcode,city) VALUES ('0919','Returprint BRC');
 insert into cityinfo (zipcode,city) VALUES ('0929','København C');
 insert into cityinfo (zipcode,city) VALUES ('0960','Internationalt Postcenter');
 insert into cityinfo (zipcode,city) VALUES ('0999','København C');
 insert into cityinfo (zipcode,city) VALUES ('1000','København K');
 insert into cityinfo (zipcode,city) VALUES ('1001','København K');
 insert into cityinfo (zipcode,city) VALUES ('1002','København K');
 insert into cityinfo (zipcode,city) VALUES ('1003','København K');
 insert into cityinfo (zipcode,city) VALUES ('1004','København K');
 insert into cityinfo (zipcode,city) VALUES ('1005','København K');
 insert into cityinfo (zipcode,city) VALUES ('1006','København K');
 insert into cityinfo (zipcode,city) VALUES ('1007','København K');
 insert into cityinfo (zipcode,city) VALUES ('1008','København K');
 insert into cityinfo (zipcode,city) VALUES ('1009','København K');
 insert into cityinfo (zipcode,city) VALUES ('1010','København K');
 insert into cityinfo (zipcode,city) VALUES ('1011','København K');
 insert into cityinfo (zipcode,city) VALUES ('1012','København K');
 insert into cityinfo (zipcode,city) VALUES ('1013','København K');
 insert into cityinfo (zipcode,city) VALUES ('1014','København K');
 insert into cityinfo (zipcode,city) VALUES ('1015','København K');
 insert into cityinfo (zipcode,city) VALUES ('1016','København K');
 insert into cityinfo (zipcode,city) VALUES ('1017','København K');
 insert into cityinfo (zipcode,city) VALUES ('1018','København K');
 insert into cityinfo (zipcode,city) VALUES ('1019','København K');
 insert into cityinfo (zipcode,city) VALUES ('1020','København K');
 insert into cityinfo (zipcode,city) VALUES ('1021','København K');
 insert into cityinfo (zipcode,city) VALUES ('1022','København K');
 insert into cityinfo (zipcode,city) VALUES ('1023','København K');
 insert into cityinfo (zipcode,city) VALUES ('1024','København K');
 insert into cityinfo (zipcode,city) VALUES ('1025','København K');
 insert into cityinfo (zipcode,city) VALUES ('1026','København K');
 insert into cityinfo (zipcode,city) VALUES ('1045','København K');
 insert into cityinfo (zipcode,city) VALUES ('1050','København K');
 insert into cityinfo (zipcode,city) VALUES ('1051','København K');
 insert into cityinfo (zipcode,city) VALUES ('1052','København K');
 insert into cityinfo (zipcode,city) VALUES ('1053','København K');
 insert into cityinfo (zipcode,city) VALUES ('1054','København K');
 insert into cityinfo (zipcode,city) VALUES ('1055','København K');
 insert into cityinfo (zipcode,city) VALUES ('1056','København K');
 insert into cityinfo (zipcode,city) VALUES ('1057','København K');
 insert into cityinfo (zipcode,city) VALUES ('1058','København K');
 insert into cityinfo (zipcode,city) VALUES ('1059','København K');
 insert into cityinfo (zipcode,city) VALUES ('1060','København K');
 insert into cityinfo (zipcode,city) VALUES ('1061','København K');
 insert into cityinfo (zipcode,city) VALUES ('1062','København K');
 insert into cityinfo (zipcode,city) VALUES ('1063','København K');
 insert into cityinfo (zipcode,city) VALUES ('1064','København K');
 insert into cityinfo (zipcode,city) VALUES ('1065','København K');
 insert into cityinfo (zipcode,city) VALUES ('1066','København K');
 insert into cityinfo (zipcode,city) VALUES ('1067','København K');
 insert into cityinfo (zipcode,city) VALUES ('1068','København K');
 insert into cityinfo (zipcode,city) VALUES ('1069','København K');
 insert into cityinfo (zipcode,city) VALUES ('1070','København K');
 insert into cityinfo (zipcode,city) VALUES ('1071','København K');
 insert into cityinfo (zipcode,city) VALUES ('1072','København K');
 insert into cityinfo (zipcode,city) VALUES ('1073','København K');
 insert into cityinfo (zipcode,city) VALUES ('1074','København K');
 insert into cityinfo (zipcode,city) VALUES ('1092','København K');
 insert into cityinfo (zipcode,city) VALUES ('1093','København K');
 insert into cityinfo (zipcode,city) VALUES ('1095','København K');
 insert into cityinfo (zipcode,city) VALUES ('1098','København K');
 insert into cityinfo (zipcode,city) VALUES ('1100','København K');
 insert into cityinfo (zipcode,city) VALUES ('1101','København K');
 insert into cityinfo (zipcode,city) VALUES ('1102','København K');
 insert into cityinfo (zipcode,city) VALUES ('1103','København K');
 insert into cityinfo (zipcode,city) VALUES ('1104','København K');
 insert into cityinfo (zipcode,city) VALUES ('1105','København K');
 insert into cityinfo (zipcode,city) VALUES ('1106','København K');
 insert into cityinfo (zipcode,city) VALUES ('1107','København K');
 insert into cityinfo (zipcode,city) VALUES ('1110','København K');
 insert into cityinfo (zipcode,city) VALUES ('1111','København K');
 insert into cityinfo (zipcode,city) VALUES ('1112','København K');
 insert into cityinfo (zipcode,city) VALUES ('1113','København K');
 insert into cityinfo (zipcode,city) VALUES ('1114','København K');
 insert into cityinfo (zipcode,city) VALUES ('1115','København K');
 insert into cityinfo (zipcode,city) VALUES ('1116','København K');
 insert into cityinfo (zipcode,city) VALUES ('1117','København K');
 insert into cityinfo (zipcode,city) VALUES ('1118','København K');
 insert into cityinfo (zipcode,city) VALUES ('1119','København K');
 insert into cityinfo (zipcode,city) VALUES ('1120','København K');
 insert into cityinfo (zipcode,city) VALUES ('1121','København K');
 insert into cityinfo (zipcode,city) VALUES ('1122','København K');
 insert into cityinfo (zipcode,city) VALUES ('1123','København K');
 insert into cityinfo (zipcode,city) VALUES ('1124','København K');
 insert into cityinfo (zipcode,city) VALUES ('1125','København K');
 insert into cityinfo (zipcode,city) VALUES ('1126','København K');
 insert into cityinfo (zipcode,city) VALUES ('1127','København K');
 insert into cityinfo (zipcode,city) VALUES ('1128','København K');
 insert into cityinfo (zipcode,city) VALUES ('1129','København K');
 insert into cityinfo (zipcode,city) VALUES ('1130','København K');
 insert into cityinfo (zipcode,city) VALUES ('1131','København K');
 insert into cityinfo (zipcode,city) VALUES ('1140','København K');
 insert into cityinfo (zipcode,city) VALUES ('1147','København K');
 insert into cityinfo (zipcode,city) VALUES ('1148','København K');
 insert into cityinfo (zipcode,city) VALUES ('1150','København K');
 insert into cityinfo (zipcode,city) VALUES ('1151','København K');
 insert into cityinfo (zipcode,city) VALUES ('1152','København K');
 insert into cityinfo (zipcode,city) VALUES ('1153','København K');
 insert into cityinfo (zipcode,city) VALUES ('1154','København K');
 insert into cityinfo (zipcode,city) VALUES ('1155','København K');
 insert into cityinfo (zipcode,city) VALUES ('1156','København K');
 insert into cityinfo (zipcode,city) VALUES ('1157','København K');
 insert into cityinfo (zipcode,city) VALUES ('1158','København K');
 insert into cityinfo (zipcode,city) VALUES ('1159','København K');
 insert into cityinfo (zipcode,city) VALUES ('1160','København K');
 insert into cityinfo (zipcode,city) VALUES ('1161','København K');
 insert into cityinfo (zipcode,city) VALUES ('1162','København K');
 insert into cityinfo (zipcode,city) VALUES ('1163','København K');
 insert into cityinfo (zipcode,city) VALUES ('1164','København K');
 insert into cityinfo (zipcode,city) VALUES ('1165','København K');
 insert into cityinfo (zipcode,city) VALUES ('1166','København K');
 insert into cityinfo (zipcode,city) VALUES ('1167','København K');
 insert into cityinfo (zipcode,city) VALUES ('1168','København K');
 insert into cityinfo (zipcode,city) VALUES ('1169','København K');
 insert into cityinfo (zipcode,city) VALUES ('1170','København K');
 insert into cityinfo (zipcode,city) VALUES ('1171','København K');
 insert into cityinfo (zipcode,city) VALUES ('1172','København K');
 insert into cityinfo (zipcode,city) VALUES ('1173','København K');
 insert into cityinfo (zipcode,city) VALUES ('1174','København K');
 insert into cityinfo (zipcode,city) VALUES ('1175','København K');
 insert into cityinfo (zipcode,city) VALUES ('1200','København K');
 insert into cityinfo (zipcode,city) VALUES ('1201','København K');
 insert into cityinfo (zipcode,city) VALUES ('1202','København K');
 insert into cityinfo (zipcode,city) VALUES ('1203','København K');
 insert into cityinfo (zipcode,city) VALUES ('1204','København K');
 insert into cityinfo (zipcode,city) VALUES ('1205','København K');
 insert into cityinfo (zipcode,city) VALUES ('1206','København K');
 insert into cityinfo (zipcode,city) VALUES ('1207','København K');
 insert into cityinfo (zipcode,city) VALUES ('1208','København K');
 insert into cityinfo (zipcode,city) VALUES ('1209','København K');
 insert into cityinfo (zipcode,city) VALUES ('1210','København K');
 insert into cityinfo (zipcode,city) VALUES ('1211','København K');
 insert into cityinfo (zipcode,city) VALUES ('1212','København K');
 insert into cityinfo (zipcode,city) VALUES ('1213','København K');
 insert into cityinfo (zipcode,city) VALUES ('1214','København K');
 insert into cityinfo (zipcode,city) VALUES ('1215','København K');
 insert into cityinfo (zipcode,city) VALUES ('1216','København K');
 insert into cityinfo (zipcode,city) VALUES ('1217','København K');
 insert into cityinfo (zipcode,city) VALUES ('1218','København K');
 insert into cityinfo (zipcode,city) VALUES ('1219','København K');
 insert into cityinfo (zipcode,city) VALUES ('1220','København K');
 insert into cityinfo (zipcode,city) VALUES ('1221','København K');
 insert into cityinfo (zipcode,city) VALUES ('1240','København K');
 insert into cityinfo (zipcode,city) VALUES ('1250','København K');
 insert into cityinfo (zipcode,city) VALUES ('1251','København K');
 insert into cityinfo (zipcode,city) VALUES ('1252','København K');
 insert into cityinfo (zipcode,city) VALUES ('1253','København K');
 insert into cityinfo (zipcode,city) VALUES ('1254','København K');
 insert into cityinfo (zipcode,city) VALUES ('1255','København K');
 insert into cityinfo (zipcode,city) VALUES ('1256','København K');
 insert into cityinfo (zipcode,city) VALUES ('1257','København K');
 insert into cityinfo (zipcode,city) VALUES ('1258','København K');
 insert into cityinfo (zipcode,city) VALUES ('1259','København K');
 insert into cityinfo (zipcode,city) VALUES ('1260','København K');
 insert into cityinfo (zipcode,city) VALUES ('1261','København K');
 insert into cityinfo (zipcode,city) VALUES ('1263','København K');
 insert into cityinfo (zipcode,city) VALUES ('1264','København K');
 insert into cityinfo (zipcode,city) VALUES ('1265','København K');
 insert into cityinfo (zipcode,city) VALUES ('1266','København K');
 insert into cityinfo (zipcode,city) VALUES ('1267','København K');
 insert into cityinfo (zipcode,city) VALUES ('1268','København K');
 insert into cityinfo (zipcode,city) VALUES ('1270','København K');
 insert into cityinfo (zipcode,city) VALUES ('1271','København K');
 insert into cityinfo (zipcode,city) VALUES ('1291','København K');
 insert into cityinfo (zipcode,city) VALUES ('1300','København K');
 insert into cityinfo (zipcode,city) VALUES ('1301','København K');
 insert into cityinfo (zipcode,city) VALUES ('1302','København K');
 insert into cityinfo (zipcode,city) VALUES ('1303','København K');
 insert into cityinfo (zipcode,city) VALUES ('1304','København K');
 insert into cityinfo (zipcode,city) VALUES ('1306','København K');
 insert into cityinfo (zipcode,city) VALUES ('1307','København K');
 insert into cityinfo (zipcode,city) VALUES ('1308','København K');
 insert into cityinfo (zipcode,city) VALUES ('1309','København K');
 insert into cityinfo (zipcode,city) VALUES ('1310','København K');
 insert into cityinfo (zipcode,city) VALUES ('1311','København K');
 insert into cityinfo (zipcode,city) VALUES ('1312','København K');
 insert into cityinfo (zipcode,city) VALUES ('1313','København K');
 insert into cityinfo (zipcode,city) VALUES ('1314','København K');
 insert into cityinfo (zipcode,city) VALUES ('1315','København K');
 insert into cityinfo (zipcode,city) VALUES ('1316','København K');
 insert into cityinfo (zipcode,city) VALUES ('1317','København K');
 insert into cityinfo (zipcode,city) VALUES ('1318','København K');
 insert into cityinfo (zipcode,city) VALUES ('1319','København K');
 insert into cityinfo (zipcode,city) VALUES ('1320','København K');
 insert into cityinfo (zipcode,city) VALUES ('1321','København K');
 insert into cityinfo (zipcode,city) VALUES ('1322','København K');
 insert into cityinfo (zipcode,city) VALUES ('1323','København K');
 insert into cityinfo (zipcode,city) VALUES ('1324','København K');
 insert into cityinfo (zipcode,city) VALUES ('1325','København K');
 insert into cityinfo (zipcode,city) VALUES ('1326','København K');
 insert into cityinfo (zipcode,city) VALUES ('1327','København K');
 insert into cityinfo (zipcode,city) VALUES ('1328','København K');
 insert into cityinfo (zipcode,city) VALUES ('1329','København K');
 insert into cityinfo (zipcode,city) VALUES ('1350','København K');
 insert into cityinfo (zipcode,city) VALUES ('1352','København K');
 insert into cityinfo (zipcode,city) VALUES ('1353','København K');
 insert into cityinfo (zipcode,city) VALUES ('1354','København K');
 insert into cityinfo (zipcode,city) VALUES ('1355','København K');
 insert into cityinfo (zipcode,city) VALUES ('1356','København K');
 insert into cityinfo (zipcode,city) VALUES ('1357','København K');
 insert into cityinfo (zipcode,city) VALUES ('1358','København K');
 insert into cityinfo (zipcode,city) VALUES ('1359','København K');
 insert into cityinfo (zipcode,city) VALUES ('1360','København K');
 insert into cityinfo (zipcode,city) VALUES ('1361','København K');
 insert into cityinfo (zipcode,city) VALUES ('1362','København K');
 insert into cityinfo (zipcode,city) VALUES ('1363','København K');
 insert into cityinfo (zipcode,city) VALUES ('1364','København K');
 insert into cityinfo (zipcode,city) VALUES ('1365','København K');
 insert into cityinfo (zipcode,city) VALUES ('1366','København K');
 insert into cityinfo (zipcode,city) VALUES ('1367','København K');
 insert into cityinfo (zipcode,city) VALUES ('1368','København K');
 insert into cityinfo (zipcode,city) VALUES ('1369','København K');
 insert into cityinfo (zipcode,city) VALUES ('1370','København K');
 insert into cityinfo (zipcode,city) VALUES ('1371','København K');
 insert into cityinfo (zipcode,city) VALUES ('1400','København K');
 insert into cityinfo (zipcode,city) VALUES ('1401','København K');
 insert into cityinfo (zipcode,city) VALUES ('1402','København K');
 insert into cityinfo (zipcode,city) VALUES ('1403','København K');
 insert into cityinfo (zipcode,city) VALUES ('1404','København K');
 insert into cityinfo (zipcode,city) VALUES ('1406','København K');
 insert into cityinfo (zipcode,city) VALUES ('1407','København K');
 insert into cityinfo (zipcode,city) VALUES ('1408','København K');
 insert into cityinfo (zipcode,city) VALUES ('1409','København K');
 insert into cityinfo (zipcode,city) VALUES ('1410','København K');
 insert into cityinfo (zipcode,city) VALUES ('1411','København K');
 insert into cityinfo (zipcode,city) VALUES ('1412','København K');
 insert into cityinfo (zipcode,city) VALUES ('1413','København K');
 insert into cityinfo (zipcode,city) VALUES ('1414','København K');
 insert into cityinfo (zipcode,city) VALUES ('1415','København K');
 insert into cityinfo (zipcode,city) VALUES ('1416','København K');
 insert into cityinfo (zipcode,city) VALUES ('1417','København K');
 insert into cityinfo (zipcode,city) VALUES ('1418','København K');
 insert into cityinfo (zipcode,city) VALUES ('1419','København K');
 insert into cityinfo (zipcode,city) VALUES ('1420','København K');
 insert into cityinfo (zipcode,city) VALUES ('1421','København K');
 insert into cityinfo (zipcode,city) VALUES ('1422','København K');
 insert into cityinfo (zipcode,city) VALUES ('1423','København K');
 insert into cityinfo (zipcode,city) VALUES ('1424','København K');
 insert into cityinfo (zipcode,city) VALUES ('1425','København K');
 insert into cityinfo (zipcode,city) VALUES ('1426','København K');
 insert into cityinfo (zipcode,city) VALUES ('1427','København K');
 insert into cityinfo (zipcode,city) VALUES ('1428','København K');
 insert into cityinfo (zipcode,city) VALUES ('1429','København K');
 insert into cityinfo (zipcode,city) VALUES ('1430','København K');
 insert into cityinfo (zipcode,city) VALUES ('1431','København K');
 insert into cityinfo (zipcode,city) VALUES ('1432','København K');
 insert into cityinfo (zipcode,city) VALUES ('1433','København K');
 insert into cityinfo (zipcode,city) VALUES ('1434','København K');
 insert into cityinfo (zipcode,city) VALUES ('1435','København K');
 insert into cityinfo (zipcode,city) VALUES ('1436','København K');
 insert into cityinfo (zipcode,city) VALUES ('1437','København K');
 insert into cityinfo (zipcode,city) VALUES ('1438','København K');
 insert into cityinfo (zipcode,city) VALUES ('1439','København K');
 insert into cityinfo (zipcode,city) VALUES ('1440','København K');
 insert into cityinfo (zipcode,city) VALUES ('1441','København K');
 insert into cityinfo (zipcode,city) VALUES ('1448','København K');
 insert into cityinfo (zipcode,city) VALUES ('1450','København K');
 insert into cityinfo (zipcode,city) VALUES ('1452','København K');
 insert into cityinfo (zipcode,city) VALUES ('1453','København K');
 insert into cityinfo (zipcode,city) VALUES ('1454','København K');
 insert into cityinfo (zipcode,city) VALUES ('1455','København K');
 insert into cityinfo (zipcode,city) VALUES ('1456','København K');
 insert into cityinfo (zipcode,city) VALUES ('1457','København K');
 insert into cityinfo (zipcode,city) VALUES ('1458','København K');
 insert into cityinfo (zipcode,city) VALUES ('1459','København K');
 insert into cityinfo (zipcode,city) VALUES ('1460','København K');
 insert into cityinfo (zipcode,city) VALUES ('1461','København K');
 insert into cityinfo (zipcode,city) VALUES ('1462','København K');
 insert into cityinfo (zipcode,city) VALUES ('1463','København K');
 insert into cityinfo (zipcode,city) VALUES ('1464','København K');
 insert into cityinfo (zipcode,city) VALUES ('1465','København K');
 insert into cityinfo (zipcode,city) VALUES ('1466','København K');
 insert into cityinfo (zipcode,city) VALUES ('1467','København K');
 insert into cityinfo (zipcode,city) VALUES ('1468','København K');
 insert into cityinfo (zipcode,city) VALUES ('1470','København K');
 insert into cityinfo (zipcode,city) VALUES ('1471','København K');
 insert into cityinfo (zipcode,city) VALUES ('1472','København K');
 insert into cityinfo (zipcode,city) VALUES ('1473','København K');
 insert into cityinfo (zipcode,city) VALUES ('1500','København V');
 insert into cityinfo (zipcode,city) VALUES ('1501','København V');
 insert into cityinfo (zipcode,city) VALUES ('1502','København V');
 insert into cityinfo (zipcode,city) VALUES ('1503','København V');
 insert into cityinfo (zipcode,city) VALUES ('1504','København V');
 insert into cityinfo (zipcode,city) VALUES ('1505','København V');
 insert into cityinfo (zipcode,city) VALUES ('1506','København V');
 insert into cityinfo (zipcode,city) VALUES ('1507','København V');
 insert into cityinfo (zipcode,city) VALUES ('1508','København V');
 insert into cityinfo (zipcode,city) VALUES ('1509','København V');
 insert into cityinfo (zipcode,city) VALUES ('1510','København V');
 insert into cityinfo (zipcode,city) VALUES ('1512','Returpost');
 insert into cityinfo (zipcode,city) VALUES ('1513','Centraltastning');
 insert into cityinfo (zipcode,city) VALUES ('1532','København V');
 insert into cityinfo (zipcode,city) VALUES ('1533','København V');
 insert into cityinfo (zipcode,city) VALUES ('1550','København V');
 insert into cityinfo (zipcode,city) VALUES ('1551','København V');
 insert into cityinfo (zipcode,city) VALUES ('1552','København V');
 insert into cityinfo (zipcode,city) VALUES ('1553','København V');
 insert into cityinfo (zipcode,city) VALUES ('1554','København V');
 insert into cityinfo (zipcode,city) VALUES ('1555','København V');
 insert into cityinfo (zipcode,city) VALUES ('1556','København V');
 insert into cityinfo (zipcode,city) VALUES ('1557','København V');
 insert into cityinfo (zipcode,city) VALUES ('1558','København V');
 insert into cityinfo (zipcode,city) VALUES ('1559','København V');
 insert into cityinfo (zipcode,city) VALUES ('1560','København V');
 insert into cityinfo (zipcode,city) VALUES ('1561','København V');
 insert into cityinfo (zipcode,city) VALUES ('1562','København V');
 insert into cityinfo (zipcode,city) VALUES ('1563','København V');
 insert into cityinfo (zipcode,city) VALUES ('1564','København V');
 insert into cityinfo (zipcode,city) VALUES ('1566','København V');
 insert into cityinfo (zipcode,city) VALUES ('1567','København V');
 insert into cityinfo (zipcode,city) VALUES ('1568','København V');
 insert into cityinfo (zipcode,city) VALUES ('1569','København V');
 insert into cityinfo (zipcode,city) VALUES ('1570','København V');
 insert into cityinfo (zipcode,city) VALUES ('1571','København V');
 insert into cityinfo (zipcode,city) VALUES ('1572','København V');
 insert into cityinfo (zipcode,city) VALUES ('1573','København V');
 insert into cityinfo (zipcode,city) VALUES ('1574','København V');
 insert into cityinfo (zipcode,city) VALUES ('1575','København V');
 insert into cityinfo (zipcode,city) VALUES ('1576','København V');
 insert into cityinfo (zipcode,city) VALUES ('1577','København V');
 insert into cityinfo (zipcode,city) VALUES ('1592','København V');
 insert into cityinfo (zipcode,city) VALUES ('1599','København V');
 insert into cityinfo (zipcode,city) VALUES ('1600','København V');
 insert into cityinfo (zipcode,city) VALUES ('1601','København V');
 insert into cityinfo (zipcode,city) VALUES ('1602','København V');
 insert into cityinfo (zipcode,city) VALUES ('1603','København V');
 insert into cityinfo (zipcode,city) VALUES ('1604','København V');
 insert into cityinfo (zipcode,city) VALUES ('1605','København V');
 insert into cityinfo (zipcode,city) VALUES ('1606','København V');
 insert into cityinfo (zipcode,city) VALUES ('1607','København V');
 insert into cityinfo (zipcode,city) VALUES ('1608','København V');
 insert into cityinfo (zipcode,city) VALUES ('1609','København V');
 insert into cityinfo (zipcode,city) VALUES ('1610','København V');
 insert into cityinfo (zipcode,city) VALUES ('1611','København V');
 insert into cityinfo (zipcode,city) VALUES ('1612','København V');
 insert into cityinfo (zipcode,city) VALUES ('1613','København V');
 insert into cityinfo (zipcode,city) VALUES ('1614','København V');
 insert into cityinfo (zipcode,city) VALUES ('1615','København V');
 insert into cityinfo (zipcode,city) VALUES ('1616','København V');
 insert into cityinfo (zipcode,city) VALUES ('1617','København V');
 insert into cityinfo (zipcode,city) VALUES ('1618','København V');
 insert into cityinfo (zipcode,city) VALUES ('1619','København V');
 insert into cityinfo (zipcode,city) VALUES ('1620','København V');
 insert into cityinfo (zipcode,city) VALUES ('1621','København V');
 insert into cityinfo (zipcode,city) VALUES ('1622','København V');
 insert into cityinfo (zipcode,city) VALUES ('1623','København V');
 insert into cityinfo (zipcode,city) VALUES ('1624','København V');
 insert into cityinfo (zipcode,city) VALUES ('1630','København V');
 insert into cityinfo (zipcode,city) VALUES ('1631','København V');
 insert into cityinfo (zipcode,city) VALUES ('1632','København V');
 insert into cityinfo (zipcode,city) VALUES ('1633','København V');
 insert into cityinfo (zipcode,city) VALUES ('1634','København V');
 insert into cityinfo (zipcode,city) VALUES ('1635','København V');
 insert into cityinfo (zipcode,city) VALUES ('1650','København V');
 insert into cityinfo (zipcode,city) VALUES ('1651','København V');
 insert into cityinfo (zipcode,city) VALUES ('1652','København V');
 insert into cityinfo (zipcode,city) VALUES ('1653','København V');
 insert into cityinfo (zipcode,city) VALUES ('1654','København V');
 insert into cityinfo (zipcode,city) VALUES ('1655','København V');
 insert into cityinfo (zipcode,city) VALUES ('1656','København V');
 insert into cityinfo (zipcode,city) VALUES ('1657','København V');
 insert into cityinfo (zipcode,city) VALUES ('1658','København V');
 insert into cityinfo (zipcode,city) VALUES ('1659','København V');
 insert into cityinfo (zipcode,city) VALUES ('1660','København V');
 insert into cityinfo (zipcode,city) VALUES ('1661','København V');
 insert into cityinfo (zipcode,city) VALUES ('1662','København V');
 insert into cityinfo (zipcode,city) VALUES ('1663','København V');
 insert into cityinfo (zipcode,city) VALUES ('1664','København V');
 insert into cityinfo (zipcode,city) VALUES ('1665','København V');
 insert into cityinfo (zipcode,city) VALUES ('1666','København V');
 insert into cityinfo (zipcode,city) VALUES ('1667','København V');
 insert into cityinfo (zipcode,city) VALUES ('1668','København V');
 insert into cityinfo (zipcode,city) VALUES ('1669','København V');
 insert into cityinfo (zipcode,city) VALUES ('1670','København V');
 insert into cityinfo (zipcode,city) VALUES ('1671','København V');
 insert into cityinfo (zipcode,city) VALUES ('1672','København V');
 insert into cityinfo (zipcode,city) VALUES ('1673','København V');
 insert into cityinfo (zipcode,city) VALUES ('1674','København V');
 insert into cityinfo (zipcode,city) VALUES ('1675','København V');
 insert into cityinfo (zipcode,city) VALUES ('1676','København V');
 insert into cityinfo (zipcode,city) VALUES ('1677','København V');
 insert into cityinfo (zipcode,city) VALUES ('1699','København V');
 insert into cityinfo (zipcode,city) VALUES ('1700','København V');
 insert into cityinfo (zipcode,city) VALUES ('1701','København V');
 insert into cityinfo (zipcode,city) VALUES ('1702','København V');
 insert into cityinfo (zipcode,city) VALUES ('1703','København V');
 insert into cityinfo (zipcode,city) VALUES ('1704','København V');
 insert into cityinfo (zipcode,city) VALUES ('1705','København V');
 insert into cityinfo (zipcode,city) VALUES ('1706','København V');
 insert into cityinfo (zipcode,city) VALUES ('1707','København V');
 insert into cityinfo (zipcode,city) VALUES ('1708','København V');
 insert into cityinfo (zipcode,city) VALUES ('1709','København V');
 insert into cityinfo (zipcode,city) VALUES ('1710','København V');
 insert into cityinfo (zipcode,city) VALUES ('1711','København V');
 insert into cityinfo (zipcode,city) VALUES ('1712','København V');
 insert into cityinfo (zipcode,city) VALUES ('1713','København V');
 insert into cityinfo (zipcode,city) VALUES ('1714','København V');
 insert into cityinfo (zipcode,city) VALUES ('1715','København V');
 insert into cityinfo (zipcode,city) VALUES ('1716','København V');
 insert into cityinfo (zipcode,city) VALUES ('1717','København V');
 insert into cityinfo (zipcode,city) VALUES ('1718','København V');
 insert into cityinfo (zipcode,city) VALUES ('1719','København V');
 insert into cityinfo (zipcode,city) VALUES ('1720','København V');
 insert into cityinfo (zipcode,city) VALUES ('1721','København V');
 insert into cityinfo (zipcode,city) VALUES ('1722','København V');
 insert into cityinfo (zipcode,city) VALUES ('1723','København V');
 insert into cityinfo (zipcode,city) VALUES ('1724','København V');
 insert into cityinfo (zipcode,city) VALUES ('1725','København V');
 insert into cityinfo (zipcode,city) VALUES ('1726','København V');
 insert into cityinfo (zipcode,city) VALUES ('1727','København V');
 insert into cityinfo (zipcode,city) VALUES ('1728','København V');
 insert into cityinfo (zipcode,city) VALUES ('1729','København V');
 insert into cityinfo (zipcode,city) VALUES ('1730','København V');
 insert into cityinfo (zipcode,city) VALUES ('1731','København V');
 insert into cityinfo (zipcode,city) VALUES ('1732','København V');
 insert into cityinfo (zipcode,city) VALUES ('1733','København V');
 insert into cityinfo (zipcode,city) VALUES ('1734','København V');
 insert into cityinfo (zipcode,city) VALUES ('1735','København V');
 insert into cityinfo (zipcode,city) VALUES ('1736','København V');
 insert into cityinfo (zipcode,city) VALUES ('1737','København V');
 insert into cityinfo (zipcode,city) VALUES ('1738','København V');
 insert into cityinfo (zipcode,city) VALUES ('1739','København V');
 insert into cityinfo (zipcode,city) VALUES ('1749','København V');
 insert into cityinfo (zipcode,city) VALUES ('1750','København V');
 insert into cityinfo (zipcode,city) VALUES ('1751','København V');
 insert into cityinfo (zipcode,city) VALUES ('1752','København V');
 insert into cityinfo (zipcode,city) VALUES ('1753','København V');
 insert into cityinfo (zipcode,city) VALUES ('1754','København V');
 insert into cityinfo (zipcode,city) VALUES ('1755','København V');
 insert into cityinfo (zipcode,city) VALUES ('1756','København V');
 insert into cityinfo (zipcode,city) VALUES ('1757','København V');
 insert into cityinfo (zipcode,city) VALUES ('1758','København V');
 insert into cityinfo (zipcode,city) VALUES ('1759','København V');
 insert into cityinfo (zipcode,city) VALUES ('1760','København V');
 insert into cityinfo (zipcode,city) VALUES ('1761','København V');
 insert into cityinfo (zipcode,city) VALUES ('1762','København V');
 insert into cityinfo (zipcode,city) VALUES ('1763','København V');
 insert into cityinfo (zipcode,city) VALUES ('1764','København V');
 insert into cityinfo (zipcode,city) VALUES ('1765','København V');
 insert into cityinfo (zipcode,city) VALUES ('1766','København V');
 insert into cityinfo (zipcode,city) VALUES ('1770','København V');
 insert into cityinfo (zipcode,city) VALUES ('1771','København V');
 insert into cityinfo (zipcode,city) VALUES ('1772','København V');
 insert into cityinfo (zipcode,city) VALUES ('1773','København V');
 insert into cityinfo (zipcode,city) VALUES ('1774','København V');
 insert into cityinfo (zipcode,city) VALUES ('1775','København V');
 insert into cityinfo (zipcode,city) VALUES ('1777','København V');
 insert into cityinfo (zipcode,city) VALUES ('1780','København V');
 insert into cityinfo (zipcode,city) VALUES ('1782','København V');
 insert into cityinfo (zipcode,city) VALUES ('1785','København V');
 insert into cityinfo (zipcode,city) VALUES ('1786','København V');
 insert into cityinfo (zipcode,city) VALUES ('1787','København V');
 insert into cityinfo (zipcode,city) VALUES ('1790','København V');
 insert into cityinfo (zipcode,city) VALUES ('1799','København V');
 insert into cityinfo (zipcode,city) VALUES ('1800','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1801','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1802','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1803','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1804','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1805','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1806','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1807','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1808','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1809','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1810','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1811','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1812','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1813','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1814','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1815','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1816','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1817','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1818','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1819','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1820','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1822','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1823','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1824','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1825','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1826','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1827','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1828','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1829','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1835','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1850','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1851','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1852','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1853','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1854','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1855','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1856','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1857','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1860','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1861','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1862','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1863','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1864','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1865','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1866','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1867','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1868','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1870','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1871','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1872','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1873','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1874','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1875','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1876','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1877','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1878','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1879','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1900','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1901','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1902','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1903','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1904','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1905','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1906','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1908','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1909','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1910','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1911','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1912','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1913','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1914','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1915','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1916','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1917','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1920','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1921','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1922','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1923','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1924','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1925','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1926','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1927','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1928','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1931','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1950','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1951','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1952','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1953','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1954','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1955','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1956','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1957','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1958','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1959','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1960','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1961','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1962','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1963','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1964','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1965','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1966','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1967','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1970','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1971','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1972','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1973','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('1974','Frederiksberg C');
 insert into cityinfo (zipcode,city) VALUES ('2000','Frederiksberg');
 insert into cityinfo (zipcode,city) VALUES ('2100','København Ø');
 insert into cityinfo (zipcode,city) VALUES ('2150','Nordhavn');
 insert into cityinfo (zipcode,city) VALUES ('2200','København N');
 insert into cityinfo (zipcode,city) VALUES ('2300','København S');
 insert into cityinfo (zipcode,city) VALUES ('2400','København NV');
 insert into cityinfo (zipcode,city) VALUES ('2450','København SV');
 insert into cityinfo (zipcode,city) VALUES ('2500','Valby');
 insert into cityinfo (zipcode,city) VALUES ('2600','Glostrup');
 insert into cityinfo (zipcode,city) VALUES ('2605','Brøndby');
 insert into cityinfo (zipcode,city) VALUES ('2610','Rødovre');
 insert into cityinfo (zipcode,city) VALUES ('2620','Albertslund');
 insert into cityinfo (zipcode,city) VALUES ('2625','Vallensbæk');
 insert into cityinfo (zipcode,city) VALUES ('2630','Taastrup');
 insert into cityinfo (zipcode,city) VALUES ('2635','Ishøj');
 insert into cityinfo (zipcode,city) VALUES ('2640','Hedehusene');
 insert into cityinfo (zipcode,city) VALUES ('2650','Hvidovre');
 insert into cityinfo (zipcode,city) VALUES ('2660','Brøndby Strand');
 insert into cityinfo (zipcode,city) VALUES ('2665','Vallensbæk Strand');
 insert into cityinfo (zipcode,city) VALUES ('2670','Greve');
 insert into cityinfo (zipcode,city) VALUES ('2680','Solrød Strand');
 insert into cityinfo (zipcode,city) VALUES ('2690','Karlslunde');
 insert into cityinfo (zipcode,city) VALUES ('2700','Brønshøj');
 insert into cityinfo (zipcode,city) VALUES ('2720','Vanløse');
 insert into cityinfo (zipcode,city) VALUES ('2730','Herlev');
 insert into cityinfo (zipcode,city) VALUES ('2740','Skovlunde');
 insert into cityinfo (zipcode,city) VALUES ('2750','Ballerup');
 insert into cityinfo (zipcode,city) VALUES ('2760','Måløv');
 insert into cityinfo (zipcode,city) VALUES ('2765','Smørum');
 insert into cityinfo (zipcode,city) VALUES ('2770','Kastrup');
 insert into cityinfo (zipcode,city) VALUES ('2791','Dragør');
 insert into cityinfo (zipcode,city) VALUES ('2800','Kongens Lyngby');
 insert into cityinfo (zipcode,city) VALUES ('2820','Gentofte');
 insert into cityinfo (zipcode,city) VALUES ('2830','Virum');
 insert into cityinfo (zipcode,city) VALUES ('2840','Holte');
 insert into cityinfo (zipcode,city) VALUES ('2850','Nærum');
 insert into cityinfo (zipcode,city) VALUES ('2860','Søborg');
 insert into cityinfo (zipcode,city) VALUES ('2870','Dyssegård');
 insert into cityinfo (zipcode,city) VALUES ('2880','Bagsværd');
 insert into cityinfo (zipcode,city) VALUES ('2900','Hellerup');
 insert into cityinfo (zipcode,city) VALUES ('2920','Charlottenlund');
 insert into cityinfo (zipcode,city) VALUES ('2930','Klampenborg');
 insert into cityinfo (zipcode,city) VALUES ('2942','Skodsborg');
 insert into cityinfo (zipcode,city) VALUES ('2950','Vedbæk');
 insert into cityinfo (zipcode,city) VALUES ('2960','Rungsted Kyst');
 insert into cityinfo (zipcode,city) VALUES ('2970','Hørsholm');
 insert into cityinfo (zipcode,city) VALUES ('2980','Kokkedal');
 insert into cityinfo (zipcode,city) VALUES ('2990','Nivå');
 insert into cityinfo (zipcode,city) VALUES ('3000','Helsingør');
 insert into cityinfo (zipcode,city) VALUES ('3050','Humlebæk');
 insert into cityinfo (zipcode,city) VALUES ('3060','Espergærde');
 insert into cityinfo (zipcode,city) VALUES ('3070','Snekkersten');
 insert into cityinfo (zipcode,city) VALUES ('3080','Tikøb');
 insert into cityinfo (zipcode,city) VALUES ('3100','Hornbæk');
 insert into cityinfo (zipcode,city) VALUES ('3120','Dronningmølle');
 insert into cityinfo (zipcode,city) VALUES ('3140','Ålsgårde');
 insert into cityinfo (zipcode,city) VALUES ('3150','Hellebæk');
 insert into cityinfo (zipcode,city) VALUES ('3200','Helsinge');
 insert into cityinfo (zipcode,city) VALUES ('3210','Vejby');
 insert into cityinfo (zipcode,city) VALUES ('3220','Tisvildeleje');
 insert into cityinfo (zipcode,city) VALUES ('3230','Græsted');
 insert into cityinfo (zipcode,city) VALUES ('3250','Gilleleje');
 insert into cityinfo (zipcode,city) VALUES ('3300','Frederiksværk');
 insert into cityinfo (zipcode,city) VALUES ('3310','Ølsted');
 insert into cityinfo (zipcode,city) VALUES ('3320','Skævinge');
 insert into cityinfo (zipcode,city) VALUES ('3330','Gørløse');
 insert into cityinfo (zipcode,city) VALUES ('3360','Liseleje');
 insert into cityinfo (zipcode,city) VALUES ('3370','Melby');
 insert into cityinfo (zipcode,city) VALUES ('3390','Hundested');
 insert into cityinfo (zipcode,city) VALUES ('3400','Hillerød');
 insert into cityinfo (zipcode,city) VALUES ('3450','Allerød');
 insert into cityinfo (zipcode,city) VALUES ('3460','Birkerød');
 insert into cityinfo (zipcode,city) VALUES ('3480','Fredensborg');
 insert into cityinfo (zipcode,city) VALUES ('3490','Kvistgård');
 insert into cityinfo (zipcode,city) VALUES ('3500','Værløse');
 insert into cityinfo (zipcode,city) VALUES ('3520','Farum');
 insert into cityinfo (zipcode,city) VALUES ('3540','Lynge');
 insert into cityinfo (zipcode,city) VALUES ('3550','Slangerup');
 insert into cityinfo (zipcode,city) VALUES ('3600','Frederikssund');
 insert into cityinfo (zipcode,city) VALUES ('3630','Jægerspris');
 insert into cityinfo (zipcode,city) VALUES ('3650','Ølstykke');
 insert into cityinfo (zipcode,city) VALUES ('3660','Stenløse');
 insert into cityinfo (zipcode,city) VALUES ('3670','Veksø Sjælland');
 insert into cityinfo (zipcode,city) VALUES ('3700','Rønne');
 insert into cityinfo (zipcode,city) VALUES ('3720','Aakirkeby');
 insert into cityinfo (zipcode,city) VALUES ('3730','Nexø');
 insert into cityinfo (zipcode,city) VALUES ('3740','Svaneke');
 insert into cityinfo (zipcode,city) VALUES ('3751','Østermarie');
 insert into cityinfo (zipcode,city) VALUES ('3760','Gudhjem');
 insert into cityinfo (zipcode,city) VALUES ('3770','Allinge');
 insert into cityinfo (zipcode,city) VALUES ('3782','Klemensker');
 insert into cityinfo (zipcode,city) VALUES ('3790','Hasle');
 insert into cityinfo (zipcode,city) VALUES ('4000','Roskilde');
 insert into cityinfo (zipcode,city) VALUES ('4030','Tune');
 insert into cityinfo (zipcode,city) VALUES ('4040','Jyllinge');
 insert into cityinfo (zipcode,city) VALUES ('4050','Skibby');
 insert into cityinfo (zipcode,city) VALUES ('4060','Kirke Såby');
 insert into cityinfo (zipcode,city) VALUES ('4070','Kirke Hyllinge');
 insert into cityinfo (zipcode,city) VALUES ('4100','Ringsted');
 insert into cityinfo (zipcode,city) VALUES ('4129','Ringsted');
 insert into cityinfo (zipcode,city) VALUES ('4130','Viby Sjælland');
 insert into cityinfo (zipcode,city) VALUES ('4140','Borup');
 insert into cityinfo (zipcode,city) VALUES ('4160','Herlufmagle');
 insert into cityinfo (zipcode,city) VALUES ('4171','Glumsø');
 insert into cityinfo (zipcode,city) VALUES ('4173','Fjenneslev');
 insert into cityinfo (zipcode,city) VALUES ('4174','Jystrup Midtsj');
 insert into cityinfo (zipcode,city) VALUES ('4180','Sorø');
 insert into cityinfo (zipcode,city) VALUES ('4190','Munke Bjergby');
 insert into cityinfo (zipcode,city) VALUES ('4200','Slagelse');
 insert into cityinfo (zipcode,city) VALUES ('4220','Korsør');
 insert into cityinfo (zipcode,city) VALUES ('4230','Skælskør');
 insert into cityinfo (zipcode,city) VALUES ('4241','Vemmelev');
 insert into cityinfo (zipcode,city) VALUES ('4242','Boeslunde');
 insert into cityinfo (zipcode,city) VALUES ('4243','Rude');
 insert into cityinfo (zipcode,city) VALUES ('4250','Fuglebjerg');
 insert into cityinfo (zipcode,city) VALUES ('4261','Dalmose');
 insert into cityinfo (zipcode,city) VALUES ('4262','Sandved');
 insert into cityinfo (zipcode,city) VALUES ('4270','Høng');
 insert into cityinfo (zipcode,city) VALUES ('4281','Gørlev');
 insert into cityinfo (zipcode,city) VALUES ('4291','Ruds Vedby');
 insert into cityinfo (zipcode,city) VALUES ('4293','Dianalund');
 insert into cityinfo (zipcode,city) VALUES ('4295','Stenlille');
 insert into cityinfo (zipcode,city) VALUES ('4296','Nyrup');
 insert into cityinfo (zipcode,city) VALUES ('4300','Holbæk');
 insert into cityinfo (zipcode,city) VALUES ('4320','Lejre');
 insert into cityinfo (zipcode,city) VALUES ('4330','Hvalsø');
 insert into cityinfo (zipcode,city) VALUES ('4340','Tølløse');
 insert into cityinfo (zipcode,city) VALUES ('4350','Ugerløse');
 insert into cityinfo (zipcode,city) VALUES ('4360','Kirke Eskilstrup');
 insert into cityinfo (zipcode,city) VALUES ('4370','Store Merløse');
 insert into cityinfo (zipcode,city) VALUES ('4390','Vipperød');
 insert into cityinfo (zipcode,city) VALUES ('4400','Kalundborg');
 insert into cityinfo (zipcode,city) VALUES ('4420','Regstrup');
 insert into cityinfo (zipcode,city) VALUES ('4440','Mørkøv');
 insert into cityinfo (zipcode,city) VALUES ('4450','Jyderup');
 insert into cityinfo (zipcode,city) VALUES ('4460','Snertinge');
 insert into cityinfo (zipcode,city) VALUES ('4470','Svebølle');
 insert into cityinfo (zipcode,city) VALUES ('4480','Store Fuglede');
 insert into cityinfo (zipcode,city) VALUES ('4490','Jerslev Sjælland');
 insert into cityinfo (zipcode,city) VALUES ('4500','Nykøbing Sj');
 insert into cityinfo (zipcode,city) VALUES ('4520','Svinninge');
 insert into cityinfo (zipcode,city) VALUES ('4532','Gislinge');
 insert into cityinfo (zipcode,city) VALUES ('4534','Hørve');
 insert into cityinfo (zipcode,city) VALUES ('4540','Fårevejle');
 insert into cityinfo (zipcode,city) VALUES ('4550','Asnæs');
 insert into cityinfo (zipcode,city) VALUES ('4560','Vig');
 insert into cityinfo (zipcode,city) VALUES ('4571','Grevinge');
 insert into cityinfo (zipcode,city) VALUES ('4572','Nørre Asmindrup');
 insert into cityinfo (zipcode,city) VALUES ('4573','Højby');
 insert into cityinfo (zipcode,city) VALUES ('4581','Rørvig');
 insert into cityinfo (zipcode,city) VALUES ('4583','Sjællands Odde');
 insert into cityinfo (zipcode,city) VALUES ('4591','Føllenslev');
 insert into cityinfo (zipcode,city) VALUES ('4592','Sejerø');
 insert into cityinfo (zipcode,city) VALUES ('4593','Eskebjerg');
 insert into cityinfo (zipcode,city) VALUES ('4600','Køge');
 insert into cityinfo (zipcode,city) VALUES ('4621','Gadstrup');
 insert into cityinfo (zipcode,city) VALUES ('4622','Havdrup');
 insert into cityinfo (zipcode,city) VALUES ('4623','Lille Skensved');
 insert into cityinfo (zipcode,city) VALUES ('4632','Bjæverskov');
 insert into cityinfo (zipcode,city) VALUES ('4640','Faxe');
 insert into cityinfo (zipcode,city) VALUES ('4652','Hårlev');
 insert into cityinfo (zipcode,city) VALUES ('4653','Karise');
 insert into cityinfo (zipcode,city) VALUES ('4654','Faxe Ladeplads');
 insert into cityinfo (zipcode,city) VALUES ('4660','Store Heddinge');
 insert into cityinfo (zipcode,city) VALUES ('4671','Strøby');
 insert into cityinfo (zipcode,city) VALUES ('4672','Klippinge');
 insert into cityinfo (zipcode,city) VALUES ('4673','Rødvig Stevns');
 insert into cityinfo (zipcode,city) VALUES ('4681','Herfølge');
 insert into cityinfo (zipcode,city) VALUES ('4682','Tureby');
 insert into cityinfo (zipcode,city) VALUES ('4683','Rønnede');
 insert into cityinfo (zipcode,city) VALUES ('4684','Holmegaard');
 insert into cityinfo (zipcode,city) VALUES ('4690','Haslev');
 insert into cityinfo (zipcode,city) VALUES ('4700','Næstved');
 insert into cityinfo (zipcode,city) VALUES ('4720','Præstø');
 insert into cityinfo (zipcode,city) VALUES ('4733','Tappernøje');
 insert into cityinfo (zipcode,city) VALUES ('4735','Mern');
 insert into cityinfo (zipcode,city) VALUES ('4736','Karrebæksminde');
 insert into cityinfo (zipcode,city) VALUES ('4750','Lundby');
 insert into cityinfo (zipcode,city) VALUES ('4760','Vordingborg');
 insert into cityinfo (zipcode,city) VALUES ('4771','Kalvehave');
 insert into cityinfo (zipcode,city) VALUES ('4772','Langebæk');
 insert into cityinfo (zipcode,city) VALUES ('4773','Stensved');
 insert into cityinfo (zipcode,city) VALUES ('4780','Stege');
 insert into cityinfo (zipcode,city) VALUES ('4791','Borre');
 insert into cityinfo (zipcode,city) VALUES ('4792','Askeby');
 insert into cityinfo (zipcode,city) VALUES ('4793','Bogø By');
 insert into cityinfo (zipcode,city) VALUES ('4800','Nykøbing F');
 insert into cityinfo (zipcode,city) VALUES ('4840','Nørre Alslev');
 insert into cityinfo (zipcode,city) VALUES ('4850','Stubbekøbing');
 insert into cityinfo (zipcode,city) VALUES ('4862','Guldborg');
 insert into cityinfo (zipcode,city) VALUES ('4863','Eskilstrup');
 insert into cityinfo (zipcode,city) VALUES ('4871','Horbelev');
 insert into cityinfo (zipcode,city) VALUES ('4872','Idestrup');
 insert into cityinfo (zipcode,city) VALUES ('4873','Væggerløse');
 insert into cityinfo (zipcode,city) VALUES ('4874','Gedser');
 insert into cityinfo (zipcode,city) VALUES ('4880','Nysted');
 insert into cityinfo (zipcode,city) VALUES ('4891','Toreby L');
 insert into cityinfo (zipcode,city) VALUES ('4892','Kettinge');
 insert into cityinfo (zipcode,city) VALUES ('4894','Øster Ulslev');
 insert into cityinfo (zipcode,city) VALUES ('4895','Errindlev');
 insert into cityinfo (zipcode,city) VALUES ('4900','Nakskov');
 insert into cityinfo (zipcode,city) VALUES ('4912','Harpelunde');
 insert into cityinfo (zipcode,city) VALUES ('4913','Horslunde');
 insert into cityinfo (zipcode,city) VALUES ('4920','Søllested');
 insert into cityinfo (zipcode,city) VALUES ('4930','Maribo');
 insert into cityinfo (zipcode,city) VALUES ('4941','Bandholm');
 insert into cityinfo (zipcode,city) VALUES ('4943','Torrig L');
 insert into cityinfo (zipcode,city) VALUES ('4944','Fejø');
 insert into cityinfo (zipcode,city) VALUES ('4951','Nørreballe');
 insert into cityinfo (zipcode,city) VALUES ('4952','Stokkemarke');
 insert into cityinfo (zipcode,city) VALUES ('4953','Vesterborg');
 insert into cityinfo (zipcode,city) VALUES ('4960','Holeby');
 insert into cityinfo (zipcode,city) VALUES ('4970','Rødby');
 insert into cityinfo (zipcode,city) VALUES ('4983','Dannemare');
 insert into cityinfo (zipcode,city) VALUES ('4990','Sakskøbing');
 insert into cityinfo (zipcode,city) VALUES ('4992','Midtsjælland USF P');
 insert into cityinfo (zipcode,city) VALUES ('5000','Odense C');
 insert into cityinfo (zipcode,city) VALUES ('5029','Odense C');
 insert into cityinfo (zipcode,city) VALUES ('5100','Odense C');
 insert into cityinfo (zipcode,city) VALUES ('5200','Odense V');
 insert into cityinfo (zipcode,city) VALUES ('5210','Odense NV');
 insert into cityinfo (zipcode,city) VALUES ('5220','Odense SØ');
 insert into cityinfo (zipcode,city) VALUES ('5230','Odense M');
 insert into cityinfo (zipcode,city) VALUES ('5240','Odense NØ');
 insert into cityinfo (zipcode,city) VALUES ('5250','Odense SV');
 insert into cityinfo (zipcode,city) VALUES ('5260','Odense S');
 insert into cityinfo (zipcode,city) VALUES ('5270','Odense N');
 insert into cityinfo (zipcode,city) VALUES ('5290','Marslev');
 insert into cityinfo (zipcode,city) VALUES ('5300','Kerteminde');
 insert into cityinfo (zipcode,city) VALUES ('5320','Agedrup');
 insert into cityinfo (zipcode,city) VALUES ('5330','Munkebo');
 insert into cityinfo (zipcode,city) VALUES ('5350','Rynkeby');
 insert into cityinfo (zipcode,city) VALUES ('5370','Mesinge');
 insert into cityinfo (zipcode,city) VALUES ('5380','Dalby');
 insert into cityinfo (zipcode,city) VALUES ('5390','Martofte');
 insert into cityinfo (zipcode,city) VALUES ('5400','Bogense');
 insert into cityinfo (zipcode,city) VALUES ('5450','Otterup');
 insert into cityinfo (zipcode,city) VALUES ('5462','Morud');
 insert into cityinfo (zipcode,city) VALUES ('5463','Harndrup');
 insert into cityinfo (zipcode,city) VALUES ('5464','Brenderup Fyn');
 insert into cityinfo (zipcode,city) VALUES ('5466','Asperup');
 insert into cityinfo (zipcode,city) VALUES ('5471','Søndersø');
 insert into cityinfo (zipcode,city) VALUES ('5474','Veflinge');
 insert into cityinfo (zipcode,city) VALUES ('5485','Skamby');
 insert into cityinfo (zipcode,city) VALUES ('5491','Blommenslyst');
 insert into cityinfo (zipcode,city) VALUES ('5492','Vissenbjerg');
 insert into cityinfo (zipcode,city) VALUES ('5500','Middelfart');
 insert into cityinfo (zipcode,city) VALUES ('5540','Ullerslev');
 insert into cityinfo (zipcode,city) VALUES ('5550','Langeskov');
 insert into cityinfo (zipcode,city) VALUES ('5560','Aarup');
 insert into cityinfo (zipcode,city) VALUES ('5580','Nørre Aaby');
 insert into cityinfo (zipcode,city) VALUES ('5591','Gelsted');
 insert into cityinfo (zipcode,city) VALUES ('5592','Ejby');
 insert into cityinfo (zipcode,city) VALUES ('5600','Faaborg');
 insert into cityinfo (zipcode,city) VALUES ('5610','Assens');
 insert into cityinfo (zipcode,city) VALUES ('5620','Glamsbjerg');
 insert into cityinfo (zipcode,city) VALUES ('5631','Ebberup');
 insert into cityinfo (zipcode,city) VALUES ('5642','Millinge');
 insert into cityinfo (zipcode,city) VALUES ('5672','Broby');
 insert into cityinfo (zipcode,city) VALUES ('5683','Haarby');
 insert into cityinfo (zipcode,city) VALUES ('5690','Tommerup');
 insert into cityinfo (zipcode,city) VALUES ('5700','Svendborg');
 insert into cityinfo (zipcode,city) VALUES ('5750','Ringe');
 insert into cityinfo (zipcode,city) VALUES ('5762','Vester Skerninge');
 insert into cityinfo (zipcode,city) VALUES ('5771','Stenstrup');
 insert into cityinfo (zipcode,city) VALUES ('5772','Kværndrup');
 insert into cityinfo (zipcode,city) VALUES ('5792','Årslev');
 insert into cityinfo (zipcode,city) VALUES ('5800','Nyborg');
 insert into cityinfo (zipcode,city) VALUES ('5853','Ørbæk');
 insert into cityinfo (zipcode,city) VALUES ('5854','Gislev');
 insert into cityinfo (zipcode,city) VALUES ('5856','Ryslinge');
 insert into cityinfo (zipcode,city) VALUES ('5863','Ferritslev Fyn');
 insert into cityinfo (zipcode,city) VALUES ('5871','Frørup');
 insert into cityinfo (zipcode,city) VALUES ('5874','Hesselager');
 insert into cityinfo (zipcode,city) VALUES ('5881','Skårup Fyn');
 insert into cityinfo (zipcode,city) VALUES ('5882','Vejstrup');
 insert into cityinfo (zipcode,city) VALUES ('5883','Oure');
 insert into cityinfo (zipcode,city) VALUES ('5884','Gudme');
 insert into cityinfo (zipcode,city) VALUES ('5892','Gudbjerg Sydfyn');
 insert into cityinfo (zipcode,city) VALUES ('5900','Rudkøbing');
 insert into cityinfo (zipcode,city) VALUES ('5932','Humble');
 insert into cityinfo (zipcode,city) VALUES ('5935','Bagenkop');
 insert into cityinfo (zipcode,city) VALUES ('5953','Tranekær');
 insert into cityinfo (zipcode,city) VALUES ('5960','Marstal');
 insert into cityinfo (zipcode,city) VALUES ('5970','Ærøskøbing');
 insert into cityinfo (zipcode,city) VALUES ('5985','Søby Ærø');
 insert into cityinfo (zipcode,city) VALUES ('6000','Kolding');
 insert into cityinfo (zipcode,city) VALUES ('6040','Egtved');
 insert into cityinfo (zipcode,city) VALUES ('6051','Almind');
 insert into cityinfo (zipcode,city) VALUES ('6052','Viuf');
 insert into cityinfo (zipcode,city) VALUES ('6064','Jordrup');
 insert into cityinfo (zipcode,city) VALUES ('6070','Christiansfeld');
 insert into cityinfo (zipcode,city) VALUES ('6091','Bjert');
 insert into cityinfo (zipcode,city) VALUES ('6092','Sønder Stenderup');
 insert into cityinfo (zipcode,city) VALUES ('6093','Sjølund');
 insert into cityinfo (zipcode,city) VALUES ('6094','Hejls');
 insert into cityinfo (zipcode,city) VALUES ('6100','Haderslev');
 insert into cityinfo (zipcode,city) VALUES ('6200','Aabenraa');
 insert into cityinfo (zipcode,city) VALUES ('6230','Rødekro');
 insert into cityinfo (zipcode,city) VALUES ('6240','Løgumkloster');
 insert into cityinfo (zipcode,city) VALUES ('6261','Bredebro');
 insert into cityinfo (zipcode,city) VALUES ('6270','Tønder');
 insert into cityinfo (zipcode,city) VALUES ('6280','Højer');
 insert into cityinfo (zipcode,city) VALUES ('6300','Gråsten');
 insert into cityinfo (zipcode,city) VALUES ('6310','Broager');
 insert into cityinfo (zipcode,city) VALUES ('6320','Egernsund');
 insert into cityinfo (zipcode,city) VALUES ('6330','Padborg');
 insert into cityinfo (zipcode,city) VALUES ('6340','Kruså');
 insert into cityinfo (zipcode,city) VALUES ('6360','Tinglev');
 insert into cityinfo (zipcode,city) VALUES ('6372','Bylderup-Bov');
 insert into cityinfo (zipcode,city) VALUES ('6392','Bolderslev');
 insert into cityinfo (zipcode,city) VALUES ('6400','Sønderborg');
 insert into cityinfo (zipcode,city) VALUES ('6430','Nordborg');
 insert into cityinfo (zipcode,city) VALUES ('6440','Augustenborg');
 insert into cityinfo (zipcode,city) VALUES ('6470','Sydals');
 insert into cityinfo (zipcode,city) VALUES ('6500','Vojens');
 insert into cityinfo (zipcode,city) VALUES ('6510','Gram');
 insert into cityinfo (zipcode,city) VALUES ('6520','Toftlund');
 insert into cityinfo (zipcode,city) VALUES ('6534','Agerskov');
 insert into cityinfo (zipcode,city) VALUES ('6535','Branderup J');
 insert into cityinfo (zipcode,city) VALUES ('6541','Bevtoft');
 insert into cityinfo (zipcode,city) VALUES ('6560','Sommersted');
 insert into cityinfo (zipcode,city) VALUES ('6580','Vamdrup');
 insert into cityinfo (zipcode,city) VALUES ('6600','Vejen');
 insert into cityinfo (zipcode,city) VALUES ('6621','Gesten');
 insert into cityinfo (zipcode,city) VALUES ('6622','Bække');
 insert into cityinfo (zipcode,city) VALUES ('6623','Vorbasse');
 insert into cityinfo (zipcode,city) VALUES ('6630','Rødding');
 insert into cityinfo (zipcode,city) VALUES ('6640','Lunderskov');
 insert into cityinfo (zipcode,city) VALUES ('6650','Brørup');
 insert into cityinfo (zipcode,city) VALUES ('6660','Lintrup');
 insert into cityinfo (zipcode,city) VALUES ('6670','Holsted');
 insert into cityinfo (zipcode,city) VALUES ('6682','Hovborg');
 insert into cityinfo (zipcode,city) VALUES ('6683','Føvling');
 insert into cityinfo (zipcode,city) VALUES ('6690','Gørding');
 insert into cityinfo (zipcode,city) VALUES ('6700','Esbjerg');
 insert into cityinfo (zipcode,city) VALUES ('6701','Esbjerg');
 insert into cityinfo (zipcode,city) VALUES ('6705','Esbjerg Ø');
 insert into cityinfo (zipcode,city) VALUES ('6710','Esbjerg V');
 insert into cityinfo (zipcode,city) VALUES ('6715','Esbjerg N');
 insert into cityinfo (zipcode,city) VALUES ('6720','Fanø');
 insert into cityinfo (zipcode,city) VALUES ('6731','Tjæreborg');
 insert into cityinfo (zipcode,city) VALUES ('6740','Bramming');
 insert into cityinfo (zipcode,city) VALUES ('6752','Glejbjerg');
 insert into cityinfo (zipcode,city) VALUES ('6753','Agerbæk');
 insert into cityinfo (zipcode,city) VALUES ('6760','Ribe');
 insert into cityinfo (zipcode,city) VALUES ('6771','Gredstedbro');
 insert into cityinfo (zipcode,city) VALUES ('6780','Skærbæk');
 insert into cityinfo (zipcode,city) VALUES ('6792','Rømø');
 insert into cityinfo (zipcode,city) VALUES ('6800','Varde');
 insert into cityinfo (zipcode,city) VALUES ('6818','Årre');
 insert into cityinfo (zipcode,city) VALUES ('6823','Ansager');
 insert into cityinfo (zipcode,city) VALUES ('6830','Nørre Nebel');
 insert into cityinfo (zipcode,city) VALUES ('6840','Oksbøl');
 insert into cityinfo (zipcode,city) VALUES ('6851','Janderup Vestj');
 insert into cityinfo (zipcode,city) VALUES ('6852','Billum');
 insert into cityinfo (zipcode,city) VALUES ('6853','Vejers Strand');
 insert into cityinfo (zipcode,city) VALUES ('6854','Henne');
 insert into cityinfo (zipcode,city) VALUES ('6855','Outrup');
 insert into cityinfo (zipcode,city) VALUES ('6857','Blåvand');
 insert into cityinfo (zipcode,city) VALUES ('6862','Tistrup');
 insert into cityinfo (zipcode,city) VALUES ('6870','Ølgod');
 insert into cityinfo (zipcode,city) VALUES ('6880','Tarm');
 insert into cityinfo (zipcode,city) VALUES ('6893','Hemmet');
 insert into cityinfo (zipcode,city) VALUES ('6900','Skjern');
 insert into cityinfo (zipcode,city) VALUES ('6920','Videbæk');
 insert into cityinfo (zipcode,city) VALUES ('6933','Kibæk');
 insert into cityinfo (zipcode,city) VALUES ('6940','Lem St');
 insert into cityinfo (zipcode,city) VALUES ('6950','Ringkøbing');
 insert into cityinfo (zipcode,city) VALUES ('6960','Hvide Sande');
 insert into cityinfo (zipcode,city) VALUES ('6971','Spjald');
 insert into cityinfo (zipcode,city) VALUES ('6973','Ørnhøj');
 insert into cityinfo (zipcode,city) VALUES ('6980','Tim');
 insert into cityinfo (zipcode,city) VALUES ('6990','Ulfborg');
 insert into cityinfo (zipcode,city) VALUES ('7000','Fredericia');
 insert into cityinfo (zipcode,city) VALUES ('7007','Fredericia');
 insert into cityinfo (zipcode,city) VALUES ('7017','Taulov Pakkecenter');
 insert into cityinfo (zipcode,city) VALUES ('7018','Pakker TLP');
 insert into cityinfo (zipcode,city) VALUES ('7029','Fredericia');
 insert into cityinfo (zipcode,city) VALUES ('7080','Børkop');
 insert into cityinfo (zipcode,city) VALUES ('7100','Vejle');
 insert into cityinfo (zipcode,city) VALUES ('7120','Vejle Øst');
 insert into cityinfo (zipcode,city) VALUES ('7130','Juelsminde');
 insert into cityinfo (zipcode,city) VALUES ('7140','Stouby');
 insert into cityinfo (zipcode,city) VALUES ('7150','Barrit');
 insert into cityinfo (zipcode,city) VALUES ('7160','Tørring');
 insert into cityinfo (zipcode,city) VALUES ('7171','Uldum');
 insert into cityinfo (zipcode,city) VALUES ('7173','Vonge');
 insert into cityinfo (zipcode,city) VALUES ('7182','Bredsten');
 insert into cityinfo (zipcode,city) VALUES ('7183','Randbøl');
 insert into cityinfo (zipcode,city) VALUES ('7184','Vandel');
 insert into cityinfo (zipcode,city) VALUES ('7190','Billund');
 insert into cityinfo (zipcode,city) VALUES ('7200','Grindsted');
 insert into cityinfo (zipcode,city) VALUES ('7250','Hejnsvig');
 insert into cityinfo (zipcode,city) VALUES ('7260','Sønder Omme');
 insert into cityinfo (zipcode,city) VALUES ('7270','Stakroge');
 insert into cityinfo (zipcode,city) VALUES ('7280','Sønder Felding');
 insert into cityinfo (zipcode,city) VALUES ('7300','Jelling');
 insert into cityinfo (zipcode,city) VALUES ('7321','Gadbjerg');
 insert into cityinfo (zipcode,city) VALUES ('7323','Give');
 insert into cityinfo (zipcode,city) VALUES ('7330','Brande');
 insert into cityinfo (zipcode,city) VALUES ('7361','Ejstrupholm');
 insert into cityinfo (zipcode,city) VALUES ('7362','Hampen');
 insert into cityinfo (zipcode,city) VALUES ('7400','Herning');
 insert into cityinfo (zipcode,city) VALUES ('7429','Herning');
 insert into cityinfo (zipcode,city) VALUES ('7430','Ikast');
 insert into cityinfo (zipcode,city) VALUES ('7441','Bording');
 insert into cityinfo (zipcode,city) VALUES ('7442','Engesvang');
 insert into cityinfo (zipcode,city) VALUES ('7451','Sunds');
 insert into cityinfo (zipcode,city) VALUES ('7470','Karup J');
 insert into cityinfo (zipcode,city) VALUES ('7480','Vildbjerg');
 insert into cityinfo (zipcode,city) VALUES ('7490','Aulum');
 insert into cityinfo (zipcode,city) VALUES ('7500','Holstebro');
 insert into cityinfo (zipcode,city) VALUES ('7540','Haderup');
 insert into cityinfo (zipcode,city) VALUES ('7550','Sørvad');
 insert into cityinfo (zipcode,city) VALUES ('7560','Hjerm');
 insert into cityinfo (zipcode,city) VALUES ('7570','Vemb');
 insert into cityinfo (zipcode,city) VALUES ('7600','Struer');
 insert into cityinfo (zipcode,city) VALUES ('7620','Lemvig');
 insert into cityinfo (zipcode,city) VALUES ('7650','Bøvlingbjerg');
 insert into cityinfo (zipcode,city) VALUES ('7660','Bækmarksbro');
 insert into cityinfo (zipcode,city) VALUES ('7673','Harboøre');
 insert into cityinfo (zipcode,city) VALUES ('7680','Thyborøn');
 insert into cityinfo (zipcode,city) VALUES ('7700','Thisted');
 insert into cityinfo (zipcode,city) VALUES ('7730','Hanstholm');
 insert into cityinfo (zipcode,city) VALUES ('7741','Frøstrup');
 insert into cityinfo (zipcode,city) VALUES ('7742','Vesløs');
 insert into cityinfo (zipcode,city) VALUES ('7752','Snedsted');
 insert into cityinfo (zipcode,city) VALUES ('7755','Bedsted Thy');
 insert into cityinfo (zipcode,city) VALUES ('7760','Hurup Thy');
 insert into cityinfo (zipcode,city) VALUES ('7770','Vestervig');
 insert into cityinfo (zipcode,city) VALUES ('7790','Thyholm');
 insert into cityinfo (zipcode,city) VALUES ('7800','Skive');
 insert into cityinfo (zipcode,city) VALUES ('7830','Vinderup');
 insert into cityinfo (zipcode,city) VALUES ('7840','Højslev');
 insert into cityinfo (zipcode,city) VALUES ('7850','Stoholm Jyll');
 insert into cityinfo (zipcode,city) VALUES ('7860','Spøttrup');
 insert into cityinfo (zipcode,city) VALUES ('7870','Roslev');
 insert into cityinfo (zipcode,city) VALUES ('7884','Fur');
 insert into cityinfo (zipcode,city) VALUES ('7900','Nykøbing M');
 insert into cityinfo (zipcode,city) VALUES ('7950','Erslev');
 insert into cityinfo (zipcode,city) VALUES ('7960','Karby');
 insert into cityinfo (zipcode,city) VALUES ('7970','Redsted M');
 insert into cityinfo (zipcode,city) VALUES ('7980','Vils');
 insert into cityinfo (zipcode,city) VALUES ('7990','Øster Assels');
 insert into cityinfo (zipcode,city) VALUES ('7992','Sydjylland/Fyn USF P');
 insert into cityinfo (zipcode,city) VALUES ('7993','Sydjylland/Fyn USF B');
 insert into cityinfo (zipcode,city) VALUES ('7996','Fakturaservice');
 insert into cityinfo (zipcode,city) VALUES ('7997','Fakturascanning');
 insert into cityinfo (zipcode,city) VALUES ('7998','Statsservice');
 insert into cityinfo (zipcode,city) VALUES ('7999','Kommunepost');
 insert into cityinfo (zipcode,city) VALUES ('8000','Aarhus C');
 insert into cityinfo (zipcode,city) VALUES ('8100','Aarhus C');
 insert into cityinfo (zipcode,city) VALUES ('8200','Aarhus N');
 insert into cityinfo (zipcode,city) VALUES ('8210','Aarhus V');
 insert into cityinfo (zipcode,city) VALUES ('8220','Brabrand');
 insert into cityinfo (zipcode,city) VALUES ('8229','Risskov Ø');
 insert into cityinfo (zipcode,city) VALUES ('8230','Åbyhøj');
 insert into cityinfo (zipcode,city) VALUES ('8240','Risskov');
 insert into cityinfo (zipcode,city) VALUES ('8245','Risskov Ø');
 insert into cityinfo (zipcode,city) VALUES ('8250','Egå');
 insert into cityinfo (zipcode,city) VALUES ('8260','Viby J');
 insert into cityinfo (zipcode,city) VALUES ('8270','Højbjerg');
 insert into cityinfo (zipcode,city) VALUES ('8300','Odder');
 insert into cityinfo (zipcode,city) VALUES ('8305','Samsø');
 insert into cityinfo (zipcode,city) VALUES ('8310','Tranbjerg J');
 insert into cityinfo (zipcode,city) VALUES ('8320','Mårslet');
 insert into cityinfo (zipcode,city) VALUES ('8330','Beder');
 insert into cityinfo (zipcode,city) VALUES ('8340','Malling');
 insert into cityinfo (zipcode,city) VALUES ('8350','Hundslund');
 insert into cityinfo (zipcode,city) VALUES ('8355','Solbjerg');
 insert into cityinfo (zipcode,city) VALUES ('8361','Hasselager');
 insert into cityinfo (zipcode,city) VALUES ('8362','Hørning');
 insert into cityinfo (zipcode,city) VALUES ('8370','Hadsten');
 insert into cityinfo (zipcode,city) VALUES ('8380','Trige');
 insert into cityinfo (zipcode,city) VALUES ('8381','Tilst');
 insert into cityinfo (zipcode,city) VALUES ('8382','Hinnerup');
 insert into cityinfo (zipcode,city) VALUES ('8400','Ebeltoft');
 insert into cityinfo (zipcode,city) VALUES ('8410','Rønde');
 insert into cityinfo (zipcode,city) VALUES ('8420','Knebel');
 insert into cityinfo (zipcode,city) VALUES ('8444','Balle');
 insert into cityinfo (zipcode,city) VALUES ('8450','Hammel');
 insert into cityinfo (zipcode,city) VALUES ('8462','Harlev J');
 insert into cityinfo (zipcode,city) VALUES ('8464','Galten');
 insert into cityinfo (zipcode,city) VALUES ('8471','Sabro');
 insert into cityinfo (zipcode,city) VALUES ('8472','Sporup');
 insert into cityinfo (zipcode,city) VALUES ('8500','Grenaa');
 insert into cityinfo (zipcode,city) VALUES ('8520','Lystrup');
 insert into cityinfo (zipcode,city) VALUES ('8530','Hjortshøj');
 insert into cityinfo (zipcode,city) VALUES ('8541','Skødstrup');
 insert into cityinfo (zipcode,city) VALUES ('8543','Hornslet');
 insert into cityinfo (zipcode,city) VALUES ('8544','Mørke');
 insert into cityinfo (zipcode,city) VALUES ('8550','Ryomgård');
 insert into cityinfo (zipcode,city) VALUES ('8560','Kolind');
 insert into cityinfo (zipcode,city) VALUES ('8570','Trustrup');
 insert into cityinfo (zipcode,city) VALUES ('8581','Nimtofte');
 insert into cityinfo (zipcode,city) VALUES ('8585','Glesborg');
 insert into cityinfo (zipcode,city) VALUES ('8586','Ørum Djurs');
 insert into cityinfo (zipcode,city) VALUES ('8592','Anholt');
 insert into cityinfo (zipcode,city) VALUES ('8600','Silkeborg');
 insert into cityinfo (zipcode,city) VALUES ('8620','Kjellerup');
 insert into cityinfo (zipcode,city) VALUES ('8632','Lemming');
 insert into cityinfo (zipcode,city) VALUES ('8641','Sorring');
 insert into cityinfo (zipcode,city) VALUES ('8643','Ans By');
 insert into cityinfo (zipcode,city) VALUES ('8653','Them');
 insert into cityinfo (zipcode,city) VALUES ('8654','Bryrup');
 insert into cityinfo (zipcode,city) VALUES ('8660','Skanderborg');
 insert into cityinfo (zipcode,city) VALUES ('8670','Låsby');
 insert into cityinfo (zipcode,city) VALUES ('8680','Ry');
 insert into cityinfo (zipcode,city) VALUES ('8700','Horsens');
 insert into cityinfo (zipcode,city) VALUES ('8721','Daugård');
 insert into cityinfo (zipcode,city) VALUES ('8722','Hedensted');
 insert into cityinfo (zipcode,city) VALUES ('8723','Løsning');
 insert into cityinfo (zipcode,city) VALUES ('8732','Hovedgård');
 insert into cityinfo (zipcode,city) VALUES ('8740','Brædstrup');
 insert into cityinfo (zipcode,city) VALUES ('8751','Gedved');
 insert into cityinfo (zipcode,city) VALUES ('8752','Østbirk');
 insert into cityinfo (zipcode,city) VALUES ('8762','Flemming');
 insert into cityinfo (zipcode,city) VALUES ('8763','Rask Mølle');
 insert into cityinfo (zipcode,city) VALUES ('8765','Klovborg');
 insert into cityinfo (zipcode,city) VALUES ('8766','Nørre Snede');
 insert into cityinfo (zipcode,city) VALUES ('8781','Stenderup');
 insert into cityinfo (zipcode,city) VALUES ('8783','Hornsyld');
 insert into cityinfo (zipcode,city) VALUES ('8800','Viborg');
 insert into cityinfo (zipcode,city) VALUES ('8830','Tjele');
 insert into cityinfo (zipcode,city) VALUES ('8831','Løgstrup');
 insert into cityinfo (zipcode,city) VALUES ('8832','Skals');
 insert into cityinfo (zipcode,city) VALUES ('8840','Rødkærsbro');
 insert into cityinfo (zipcode,city) VALUES ('8850','Bjerringbro');
 insert into cityinfo (zipcode,city) VALUES ('8860','Ulstrup');
 insert into cityinfo (zipcode,city) VALUES ('8870','Langå');
 insert into cityinfo (zipcode,city) VALUES ('8881','Thorsø');
 insert into cityinfo (zipcode,city) VALUES ('8882','Fårvang');
 insert into cityinfo (zipcode,city) VALUES ('8883','Gjern');
 insert into cityinfo (zipcode,city) VALUES ('8900','Randers C');
 insert into cityinfo (zipcode,city) VALUES ('8920','Randers NV');
 insert into cityinfo (zipcode,city) VALUES ('8930','Randers NØ');
 insert into cityinfo (zipcode,city) VALUES ('8940','Randers SV');
 insert into cityinfo (zipcode,city) VALUES ('8950','Ørsted');
 insert into cityinfo (zipcode,city) VALUES ('8960','Randers SØ');
 insert into cityinfo (zipcode,city) VALUES ('8961','Allingåbro');
 insert into cityinfo (zipcode,city) VALUES ('8963','Auning');
 insert into cityinfo (zipcode,city) VALUES ('8970','Havndal');
 insert into cityinfo (zipcode,city) VALUES ('8981','Spentrup');
 insert into cityinfo (zipcode,city) VALUES ('8983','Gjerlev J');
 insert into cityinfo (zipcode,city) VALUES ('8990','Fårup');
 insert into cityinfo (zipcode,city) VALUES ('9000','Aalborg');
 insert into cityinfo (zipcode,city) VALUES ('9029','Aalborg');
 insert into cityinfo (zipcode,city) VALUES ('9100','Aalborg');
 insert into cityinfo (zipcode,city) VALUES ('9200','Aalborg SV');
 insert into cityinfo (zipcode,city) VALUES ('9210','Aalborg SØ');
 insert into cityinfo (zipcode,city) VALUES ('9220','Aalborg Øst');
 insert into cityinfo (zipcode,city) VALUES ('9230','Svenstrup J');
 insert into cityinfo (zipcode,city) VALUES ('9240','Nibe');
 insert into cityinfo (zipcode,city) VALUES ('9260','Gistrup');
 insert into cityinfo (zipcode,city) VALUES ('9270','Klarup');
 insert into cityinfo (zipcode,city) VALUES ('9280','Storvorde');
 insert into cityinfo (zipcode,city) VALUES ('9293','Kongerslev');
 insert into cityinfo (zipcode,city) VALUES ('9300','Sæby');
 insert into cityinfo (zipcode,city) VALUES ('9310','Vodskov');
 insert into cityinfo (zipcode,city) VALUES ('9320','Hjallerup');
 insert into cityinfo (zipcode,city) VALUES ('9330','Dronninglund');
 insert into cityinfo (zipcode,city) VALUES ('9340','Asaa');
 insert into cityinfo (zipcode,city) VALUES ('9352','Dybvad');
 insert into cityinfo (zipcode,city) VALUES ('9362','Gandrup');
 insert into cityinfo (zipcode,city) VALUES ('9370','Hals');
 insert into cityinfo (zipcode,city) VALUES ('9380','Vestbjerg');
 insert into cityinfo (zipcode,city) VALUES ('9381','Sulsted');
 insert into cityinfo (zipcode,city) VALUES ('9382','Tylstrup');
 insert into cityinfo (zipcode,city) VALUES ('9400','Nørresundby');
 insert into cityinfo (zipcode,city) VALUES ('9430','Vadum');
 insert into cityinfo (zipcode,city) VALUES ('9440','Aabybro');
 insert into cityinfo (zipcode,city) VALUES ('9460','Brovst');
 insert into cityinfo (zipcode,city) VALUES ('9480','Løkken');
 insert into cityinfo (zipcode,city) VALUES ('9490','Pandrup');
 insert into cityinfo (zipcode,city) VALUES ('9492','Blokhus');
 insert into cityinfo (zipcode,city) VALUES ('9493','Saltum');
 insert into cityinfo (zipcode,city) VALUES ('9500','Hobro');
 insert into cityinfo (zipcode,city) VALUES ('9510','Arden');
 insert into cityinfo (zipcode,city) VALUES ('9520','Skørping');
 insert into cityinfo (zipcode,city) VALUES ('9530','Støvring');
 insert into cityinfo (zipcode,city) VALUES ('9541','Suldrup');
 insert into cityinfo (zipcode,city) VALUES ('9550','Mariager');
 insert into cityinfo (zipcode,city) VALUES ('9560','Hadsund');
 insert into cityinfo (zipcode,city) VALUES ('9574','Bælum');
 insert into cityinfo (zipcode,city) VALUES ('9575','Terndrup');
 insert into cityinfo (zipcode,city) VALUES ('9600','Aars');
 insert into cityinfo (zipcode,city) VALUES ('9610','Nørager');
 insert into cityinfo (zipcode,city) VALUES ('9620','Aalestrup');
 insert into cityinfo (zipcode,city) VALUES ('9631','Gedsted');
 insert into cityinfo (zipcode,city) VALUES ('9632','Møldrup');
 insert into cityinfo (zipcode,city) VALUES ('9640','Farsø');
 insert into cityinfo (zipcode,city) VALUES ('9670','Løgstør');
 insert into cityinfo (zipcode,city) VALUES ('9681','Ranum');
 insert into cityinfo (zipcode,city) VALUES ('9690','Fjerritslev');
 insert into cityinfo (zipcode,city) VALUES ('9700','Brønderslev');
 insert into cityinfo (zipcode,city) VALUES ('9740','Jerslev J');
 insert into cityinfo (zipcode,city) VALUES ('9750','Østervrå');
 insert into cityinfo (zipcode,city) VALUES ('9760','Vrå');
 insert into cityinfo (zipcode,city) VALUES ('9800','Hjørring');
 insert into cityinfo (zipcode,city) VALUES ('9830','Tårs');
 insert into cityinfo (zipcode,city) VALUES ('9850','Hirtshals');
 insert into cityinfo (zipcode,city) VALUES ('9870','Sindal');
 insert into cityinfo (zipcode,city) VALUES ('9881','Bindslev');
 insert into cityinfo (zipcode,city) VALUES ('9900','Frederikshavn');
 insert into cityinfo (zipcode,city) VALUES ('9940','Læsø');
 insert into cityinfo (zipcode,city) VALUES ('9970','Strandby');
 insert into cityinfo (zipcode,city) VALUES ('9981','Jerup');
 insert into cityinfo (zipcode,city) VALUES ('9982','Ålbæk');
 insert into cityinfo (zipcode,city) VALUES ('9990','Skagen');
 insert into cityinfo (zipcode,city) VALUES ('9992','Jylland USF P');
 insert into cityinfo (zipcode,city) VALUES ('9993','Jylland USF B');
 insert into cityinfo (zipcode,city) VALUES ('9996','Fakturaservice');
 insert into cityinfo (zipcode,city) VALUES ('9997','Fakturascanning');
 insert into cityinfo (zipcode,city) VALUES ('9998','Borgerservice');
 insert into cityinfo (zipcode,city) VALUES ('2412','Santa Claus/Julemanden');
 insert into cityinfo (zipcode,city) VALUES ('3900','Nuuk');
 insert into cityinfo (zipcode,city) VALUES ('3905','Nuussuaq');
 insert into cityinfo (zipcode,city) VALUES ('3910','Kangerlussuaq');
 insert into cityinfo (zipcode,city) VALUES ('3911','Sisimiut');
 insert into cityinfo (zipcode,city) VALUES ('3912','Maniitsoq');
 insert into cityinfo (zipcode,city) VALUES ('3913','Tasiilaq');
 insert into cityinfo (zipcode,city) VALUES ('3915','Kulusuk');
 insert into cityinfo (zipcode,city) VALUES ('3919','Alluitsup Paa');
 insert into cityinfo (zipcode,city) VALUES ('3920','Qaqortoq');
 insert into cityinfo (zipcode,city) VALUES ('3921','Narsaq');
 insert into cityinfo (zipcode,city) VALUES ('3922','Nanortalik');
 insert into cityinfo (zipcode,city) VALUES ('3923','Narsarsuaq');
 insert into cityinfo (zipcode,city) VALUES ('3924','Ikerasassuaq');
 insert into cityinfo (zipcode,city) VALUES ('3930','Kangilinnguit');
 insert into cityinfo (zipcode,city) VALUES ('3932','Arsuk');
 insert into cityinfo (zipcode,city) VALUES ('3940','Paamiut');
 insert into cityinfo (zipcode,city) VALUES ('3950','Aasiaat');
 insert into cityinfo (zipcode,city) VALUES ('3951','Qasigiannguit');
 insert into cityinfo (zipcode,city) VALUES ('3952','Ilulissat');
 insert into cityinfo (zipcode,city) VALUES ('3953','Qeqertarsuaq');
 insert into cityinfo (zipcode,city) VALUES ('3955','Kangaatsiaq');
 insert into cityinfo (zipcode,city) VALUES ('3961','Uummannaq');
 insert into cityinfo (zipcode,city) VALUES ('3962','Upernavik');
 insert into cityinfo (zipcode,city) VALUES ('3964','Qaarsut');
 insert into cityinfo (zipcode,city) VALUES ('3970','Pituffik');
 insert into cityinfo (zipcode,city) VALUES ('3971','Qaanaaq');
 insert into cityinfo (zipcode,city) VALUES ('3972','Station Nord');
 insert into cityinfo (zipcode,city) VALUES ('3980','Ittoqqortoormiit');
 insert into cityinfo (zipcode,city) VALUES ('3982','Mestersvig');
 insert into cityinfo (zipcode,city) VALUES ('3984','Danmarkshavn');
 insert into cityinfo (zipcode,city) VALUES ('3985','Constable Pynt');
 insert into cityinfo (zipcode,city) VALUES ('3992','Slædepatrulje Sirius');
 insert into cityinfo (zipcode,city) VALUES ('100','Tórshavn');
 insert into cityinfo (zipcode,city) VALUES ('110','Tórshavn ');
 insert into cityinfo (zipcode,city) VALUES ('160','Argir');
 insert into cityinfo (zipcode,city) VALUES ('165','Argir ');
 insert into cityinfo (zipcode,city) VALUES ('175','Kirkjubøur');
 insert into cityinfo (zipcode,city) VALUES ('176','Velbastadur');
 insert into cityinfo (zipcode,city) VALUES ('177','Sydradalur, Streymoy');
 insert into cityinfo (zipcode,city) VALUES ('178','Nordradalur');
 insert into cityinfo (zipcode,city) VALUES ('180','Kaldbak');
 insert into cityinfo (zipcode,city) VALUES ('185','Kaldbaksbotnur');
 insert into cityinfo (zipcode,city) VALUES ('186','Sund');
 insert into cityinfo (zipcode,city) VALUES ('187','Hvitanes');
 insert into cityinfo (zipcode,city) VALUES ('188','Hoyvík');
 insert into cityinfo (zipcode,city) VALUES ('210','Sandur');
 insert into cityinfo (zipcode,city) VALUES ('215','Sandur');
 insert into cityinfo (zipcode,city) VALUES ('220','Skálavík');
 insert into cityinfo (zipcode,city) VALUES ('230','Húsavík');
 insert into cityinfo (zipcode,city) VALUES ('235','Dalur');
 insert into cityinfo (zipcode,city) VALUES ('236','Skarvanes');
 insert into cityinfo (zipcode,city) VALUES ('240','Skopun');
 insert into cityinfo (zipcode,city) VALUES ('260','Skúvoy');
 insert into cityinfo (zipcode,city) VALUES ('270','Nólsoy');
 insert into cityinfo (zipcode,city) VALUES ('280','Hestur');
 insert into cityinfo (zipcode,city) VALUES ('285','Koltur');
 insert into cityinfo (zipcode,city) VALUES ('286','Stóra Dimun');
 insert into cityinfo (zipcode,city) VALUES ('330','Stykkid');
 insert into cityinfo (zipcode,city) VALUES ('335','Leynar');
 insert into cityinfo (zipcode,city) VALUES ('336','Skællingur');
 insert into cityinfo (zipcode,city) VALUES ('340','Kvívík');
 insert into cityinfo (zipcode,city) VALUES ('350','Vestmanna');
 insert into cityinfo (zipcode,city) VALUES ('355','Vestmanna');
 insert into cityinfo (zipcode,city) VALUES ('358','Válur');
 insert into cityinfo (zipcode,city) VALUES ('360','Sandavágur');
 insert into cityinfo (zipcode,city) VALUES ('370','Midvágur');
 insert into cityinfo (zipcode,city) VALUES ('375','Midvágur');
 insert into cityinfo (zipcode,city) VALUES ('380','Sørvágur');
 insert into cityinfo (zipcode,city) VALUES ('385','Vatnsoyrar');
 insert into cityinfo (zipcode,city) VALUES ('386','Bøur');
 insert into cityinfo (zipcode,city) VALUES ('387','Gásadalur');
 insert into cityinfo (zipcode,city) VALUES ('388','Mykines');
 insert into cityinfo (zipcode,city) VALUES ('400','Oyrarbakki');
 insert into cityinfo (zipcode,city) VALUES ('405','Oyrarbakki');
 insert into cityinfo (zipcode,city) VALUES ('410','Kollafjørdur');
 insert into cityinfo (zipcode,city) VALUES ('415','Oyrareingir');
 insert into cityinfo (zipcode,city) VALUES ('416','Signabøur');
 insert into cityinfo (zipcode,city) VALUES ('420','Hósvík');
 insert into cityinfo (zipcode,city) VALUES ('430','Hvalvík');
 insert into cityinfo (zipcode,city) VALUES ('435','Streymnes');
 insert into cityinfo (zipcode,city) VALUES ('436','Saksun');
 insert into cityinfo (zipcode,city) VALUES ('437','Nesvík');
 insert into cityinfo (zipcode,city) VALUES ('438','Langasandur');
 insert into cityinfo (zipcode,city) VALUES ('440','Haldarsvík');
 insert into cityinfo (zipcode,city) VALUES ('445','Tjørnuvík');
 insert into cityinfo (zipcode,city) VALUES ('450','Oyri');
 insert into cityinfo (zipcode,city) VALUES ('460','Nordskáli');
 insert into cityinfo (zipcode,city) VALUES ('465','Svináir');
 insert into cityinfo (zipcode,city) VALUES ('466','Ljósá');
 insert into cityinfo (zipcode,city) VALUES ('470','Eidi');
 insert into cityinfo (zipcode,city) VALUES ('475','Funningur');
 insert into cityinfo (zipcode,city) VALUES ('476','Gjógv');
 insert into cityinfo (zipcode,city) VALUES ('477','Funningsfjørdur');
 insert into cityinfo (zipcode,city) VALUES ('478','Elduvík');
 insert into cityinfo (zipcode,city) VALUES ('480','Skáli');
 insert into cityinfo (zipcode,city) VALUES ('485','Skálafjørdur');
 insert into cityinfo (zipcode,city) VALUES ('490','Strendur');
 insert into cityinfo (zipcode,city) VALUES ('494','Innan Glyvur');
 insert into cityinfo (zipcode,city) VALUES ('495','Kolbanargjógv');
 insert into cityinfo (zipcode,city) VALUES ('496','Morskranes');
 insert into cityinfo (zipcode,city) VALUES ('497','Selatrad');
 insert into cityinfo (zipcode,city) VALUES ('510','Gøta');
 insert into cityinfo (zipcode,city) VALUES ('511','Gøtugjógv');
 insert into cityinfo (zipcode,city) VALUES ('512','Nordragøta');
 insert into cityinfo (zipcode,city) VALUES ('513','Sydrugøta');
 insert into cityinfo (zipcode,city) VALUES ('515','Gøta');
 insert into cityinfo (zipcode,city) VALUES ('520','Leirvík');
 insert into cityinfo (zipcode,city) VALUES ('530','Fuglafjørdur');
 insert into cityinfo (zipcode,city) VALUES ('535','Fuglafjørdur');
 insert into cityinfo (zipcode,city) VALUES ('600','Saltangará');
 insert into cityinfo (zipcode,city) VALUES ('610','Saltangará');
 insert into cityinfo (zipcode,city) VALUES ('620','Runavík');
 insert into cityinfo (zipcode,city) VALUES ('625','Glyvrar');
 insert into cityinfo (zipcode,city) VALUES ('626','Lambareidi');
 insert into cityinfo (zipcode,city) VALUES ('627','Lambi');
 insert into cityinfo (zipcode,city) VALUES ('640','Rituvík');
 insert into cityinfo (zipcode,city) VALUES ('645','Æduvík');
 insert into cityinfo (zipcode,city) VALUES ('650','Toftir');
 insert into cityinfo (zipcode,city) VALUES ('655','Nes, Eysturoy');
 insert into cityinfo (zipcode,city) VALUES ('656','Saltnes');
 insert into cityinfo (zipcode,city) VALUES ('660','Søldarfjørdur');
 insert into cityinfo (zipcode,city) VALUES ('665','Skipanes');
 insert into cityinfo (zipcode,city) VALUES ('666','Gøtueidi');
 insert into cityinfo (zipcode,city) VALUES ('690','Oyndarfjørdur');
 insert into cityinfo (zipcode,city) VALUES ('695','Hellur');
 insert into cityinfo (zipcode,city) VALUES ('700','Klaksvík');
 insert into cityinfo (zipcode,city) VALUES ('710','Klaksvík');
 insert into cityinfo (zipcode,city) VALUES ('725','Nordoyri');
 insert into cityinfo (zipcode,city) VALUES ('726','Ánir');
 insert into cityinfo (zipcode,city) VALUES ('727','Árnafjørdur');
 insert into cityinfo (zipcode,city) VALUES ('730','Norddepil');
 insert into cityinfo (zipcode,city) VALUES ('735','Depil');
 insert into cityinfo (zipcode,city) VALUES ('736','Nordtoftir');
 insert into cityinfo (zipcode,city) VALUES ('737','Múli');
 insert into cityinfo (zipcode,city) VALUES ('740','Hvannasund');
 insert into cityinfo (zipcode,city) VALUES ('750','Vidareidi');
 insert into cityinfo (zipcode,city) VALUES ('765','Svinoy');
 insert into cityinfo (zipcode,city) VALUES ('766','Kirkja');
 insert into cityinfo (zipcode,city) VALUES ('767','Hattarvík');
 insert into cityinfo (zipcode,city) VALUES ('780','Kunoy');
 insert into cityinfo (zipcode,city) VALUES ('785','Haraldssund');
 insert into cityinfo (zipcode,city) VALUES ('795','Sydradalur, Kalsoy');
 insert into cityinfo (zipcode,city) VALUES ('796','Húsar');
 insert into cityinfo (zipcode,city) VALUES ('797','Mikladalur');
 insert into cityinfo (zipcode,city) VALUES ('798','Trøllanes');
 insert into cityinfo (zipcode,city) VALUES ('800','Tvøroyri');
 insert into cityinfo (zipcode,city) VALUES ('810','Tvøroyri');
 insert into cityinfo (zipcode,city) VALUES ('825','Frodba');
 insert into cityinfo (zipcode,city) VALUES ('826','Trongisvágur');
 insert into cityinfo (zipcode,city) VALUES ('827','Øravík');
 insert into cityinfo (zipcode,city) VALUES ('850','Hvalba');
 insert into cityinfo (zipcode,city) VALUES ('860','Sandvík');
 insert into cityinfo (zipcode,city) VALUES ('870','Fámjin');
 insert into cityinfo (zipcode,city) VALUES ('900','Vágur');
 insert into cityinfo (zipcode,city) VALUES ('910','Vágur');
 insert into cityinfo (zipcode,city) VALUES ('925','Nes, Vágur');
 insert into cityinfo (zipcode,city) VALUES ('926','Lopra');
 insert into cityinfo (zipcode,city) VALUES ('927','Akrar');
 insert into cityinfo (zipcode,city) VALUES ('928','Vikarbyrgi');
 insert into cityinfo (zipcode,city) VALUES ('950','Porkeri');
 insert into cityinfo (zipcode,city) VALUES ('960','Hov');
 insert into cityinfo (zipcode,city) VALUES ('970','Sumba');
 insert into cityinfo (zipcode,city) VALUES ('','undefined');
