//get all persons
GET http://localhost:8080/CA1_war_exploded/api/person/all

###
//get person by id
GET http://localhost:8080/CA1_war_exploded/api/person/2

###
//get persons by hobby
GET http://localhost:8080/CA1_war_exploded/api/person/hobby/Fodbold

###
//get persons by phone number
GET http://localhost:8080/CA1_war_exploded/api/person/phone/11111111

###
//delete person by id and get the deleted person
DELETE http://localhost:8080/CA1_war_exploded/api/person/delete/7

###
//edit person by id and get the edited person
PUT http://localhost:8080/CA1_war_exploded/api/person/edit/2
Content-Type: application/json

{
  "id": 2,
  "firstname": "Lars",
  "lastname": "Larsen",
  "email": "Email 2",
  "phones": [],
  "address": {
    "id": 1,
    "street": "street 1",
    "additionalInfo": "",
    "city": "Herning",
    "zipcode": "7400"
  },
  "hobbies": []
}

###
//create person by id and get the created person
POST http://localhost:8080/CA1_war_exploded/api/person/create
Content-Type: application/json

{
  "id": 6,
  "firstname": "Frank",
  "lastname": "F.",
  "email": "frank@freeky.com",
  "phones": [
    {
      "id": 5,
      "number": "55555555",
      "description": "Mobil"
    }
  ],
  "address": {
    "id": 5,
    "street": "Herlevvej",
    "additionalInfo": "5",
    "city": "Herning",
    "zipcode": "7400"
  },
  "hobbies": [
    {
      "id": 1,
      "description": "https://en.wikipedia.org/wiki/Table_football",
      "name": "Bordfodbold"
    },
    {
      "id": 2,
      "description": "https://en.wikipedia.org/wiki/Soccer",
      "name": "Fodbold"
    }
  ]
}